#!/usr/bin/env python3
"""
Batch 3A Revised Import Script
- UPDATE: 27 pages (3 per book, 9 books) using Page IDs
- CREATE: 63 pages (7 per book, 9 books) using Book IDs
"""

import asyncio
import os
import sys
from motor.motor_asyncio import AsyncIOMotorClient
import uuid
from datetime import datetime, timezone

# Book data with UPDATE and CREATE operations
BOOKS_DATA = [
    {
        "title": "Cooking Adventures with Chef Cat",
        "book_id": "a81c3db4-5aaf-4afc-8834-9c6566de5d7e",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "360f0a71-106e-4324-b3bb-0a7018b5b2c3", "text": "Chef Cat wore a tiny white hat and an apron splattered with tomato sauce. Every morning she padded into her kitchen, whiskers twitching at the glorious smells drifting from her pots and pans. Today was the most special morning she could remember — she was going to teach her dearest animal friends how to cook for the very first time. She tied on her apron with a double knot, stirred her biggest bubbling pot, and called out through the open window: 'Come in, come in! The kitchen is warm and the adventure is about to begin!'"},
            {"page_number": 2, "operation": "UPDATE", "page_id": "8d78a919-63ae-446a-a968-9040c0610dce", "text": "First came Rabbit, hopping in with a basket of bright orange carrots fresh from the garden, dirt still on her paws. Then Mouse arrived, so small she needed a little stool just to reach the counter — she carried a notebook for writing down every recipe. Finally Bear stomped through the door wearing an apron that was at least three sizes too small, the strings barely tying at the back. Chef Cat smiled warmly at each of them. 'Today we make carrot soup,' she announced, clapping her paws together. 'And everyone has a very important job!'"},
            {"page_number": 3, "operation": "UPDATE", "page_id": "651387c7-481d-4654-9f66-277173cded93", "text": "Rabbit took the chopping board and began — chop, chop, chop — turning the carrots into neat orange coins. Mouse measured out the spices with her tiny careful paws: a pinch of ginger, a shake of pepper, a small spoonful of honey. Bear stirred the great big pot round and round with an enormous wooden spoon, his tongue poking out with concentration. 'Cooking is all about working together,' said Chef Cat, watching each of them proudly. 'Every single ingredient matters. Every helping paw makes the meal better.' The kitchen filled with a warm and wonderful smell."},
            {"page_number": 4, "operation": "CREATE", "text": "Then disaster struck. Bear stirred so enthusiastically that a great wave of soup splashed right over the edge of the pot and onto the kitchen floor. Mouse squeaked and jumped back. Rabbit gasped. Bear's ears drooped all the way down and he looked ready to cry. 'I've ruined it,' he said in a very small voice for such a very large bear. But Chef Cat simply laughed, reached calmly for a cloth, and began mopping up. 'Every cook in the world has spilled something,' she said cheerfully. 'The secret is to simply keep going.'"},
            {"page_number": 5, "operation": "CREATE", "text": "They cleaned up together — Rabbit mopping, Mouse wringing out the cloth with her tiny paws, Bear carefully checking the pot still had enough soup inside. It did. They tasted it cautiously from small spoons. The soup was warm and sweet and the ginger gave it a lovely gentle heat. 'It's wonderful,' said Rabbit, eyes wide. 'It tastes like autumn,' said Mouse, writing this down carefully in her notebook. Bear had three spoonfuls without saying anything at all, which everyone agreed was the best possible review."},
            {"page_number": 6, "operation": "CREATE", "text": "Chef Cat showed them what to do next. The soup needed to be blended until it was perfectly smooth and velvety. She passed the blending stick carefully to each of them in turn. Rabbit blended too fast and made it splatter. Mouse blended very carefully and did it perfectly. Bear blended with one paw while eating a carrot he'd found on the counter with the other. 'Focus, Bear,' said Chef Cat. Bear put the carrot down with great dignity. The soup became smooth and golden and absolutely beautiful."},
            {"page_number": 7, "operation": "CREATE", "text": "Now came the toppings — Chef Cat's favourite part. She set out little bowls of things: a swirl of cream, chopped fresh herbs that smelled of the garden, a sprinkle of toasted seeds that crackled satisfyingly between the teeth. Each of them decorated their own bowl. Mouse made a very precise pattern with the herbs. Rabbit added extra cream. Bear put a bit of everything on, some of it in the soup and some of it beside the soup, and pronounced this 'experimental presentation.' Chef Cat said it was very advanced."},
            {"page_number": 8, "operation": "CREATE", "text": "They sat around the kitchen table together, four friends and four bowls of soup they had made with their own hands and paws. The kitchen was warm and smelled of ginger and herbs and happiness. Outside, the autumn wind blew leaves past the window. Inside, spoons clinked against bowls. Nobody spoke for a little while because they were too busy eating. 'I didn't know I could make something this good,' Rabbit said eventually. 'I didn't know cooking felt like this,' said Mouse softly, closing her notebook because some moments don't need to be written down."},
            {"page_number": 9, "operation": "CREATE", "text": "After the washing up — which Bear did, insisting, though the bowls looked rather small in his great paws — they sat together with cups of warm tea. Chef Cat pulled out her recipe book and showed them the next recipe she planned to teach: a layered vegetable pie with a golden pastry top. Rabbit's eyes went wide. Mouse immediately reopened her notebook. Bear leaned forward with an expression of absolute serious dedication. 'Same time next week?' said Chef Cat. Three voices answered at once: 'Yes please.'"},
            {"page_number": 10, "operation": "CREATE", "text": "Walking home through the autumn leaves, each of them carried something. Rabbit carried the leftover soup in a jar for her supper. Mouse carried her recipe notebook, now with four new pages filled. Bear carried the wooden spoon, which Chef Cat had given him as a gift because he had stirred with such commitment. And all three of them carried something that couldn't be put in a jar or a notebook or held in a paw — the warm knowledge that they had made something wonderful together, and that next week, they would make something wonderful again. THE END"},
        ]
    },
    {
        "title": "Friendship Island",
        "book_id": "4f09ecbf-fc70-404a-838d-c1c547c73450",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "3326c731-18d2-4114-b557-cae30f876bbc", "text": "Out in the sparkling blue sea sat a little island where only one child lived. Her name was Isla, and she had everything she could possibly want — tall coconut trees, a sandy beach that turned gold at sunset, a cosy hut with a roof of woven palm leaves, and a boat she had learned to sail herself. But she had no friends. Each evening Isla sat on the shore watching the horizon, wishing with her whole heart that someone might one day sail her way."},
            {"page_number": 2, "operation": "UPDATE", "page_id": "35283530-0909-4a15-8047-02a00ebc70e1", "text": "One morning Isla spotted something bobbing in the waves — a glass bottle with a rolled paper inside. She waded in and grabbed it, heart hammering. The note read: 'Hello! My name is Leo. I live on the island to the east, just past the reef with the red coral. I am also lonely. Would you like to be friends? Please write back.' Isla stared at the words. Then she ran back to her hut, found her best paper and her sharpest pencil, and wrote the longest letter she had ever written."},
            {"page_number": 3, "operation": "UPDATE", "page_id": "934084f4-e2eb-490a-99e9-99d0d3d155ab", "text": "Letters flew back and forth across the water in bottles, sometimes taking days, sometimes arriving the very next morning depending on the tides. Isla learned that Leo loved drawing maps and had a pet crab named Pinchy who stole his pencils. Leo learned that Isla could climb any tree on her island and always greeted the seagulls by name. Their letters grew longer every time. They wrote about their days, their thoughts, their favourite things about living on an island and the things they missed about living near other people."},
            {"page_number": 4, "operation": "CREATE", "text": "Isla began to look forward to checking the beach each morning more than anything else. On the days when a bottle was there, she would sit on the sand immediately and read without moving until she had finished every word. On the days when no bottle had arrived, she would sit for a while anyway, watching the direction of Leo's island, wondering what he was doing. She wrote him a letter about this and he wrote back: 'I do the same thing. I've named the gap of sea between us the Friendship Channel.' Isla thought this was the best name she had ever heard."},
            {"page_number": 5, "operation": "CREATE", "text": "One letter contained a drawing — a careful, detailed map of Leo's island, with every tree and rock and the little crab pool where Pinchy lived labelled in tiny precise handwriting. Isla pinned it to the wall of her hut and looked at it every day. She drew one of her own island in return, marking the tallest coconut tree (she called it the Observatory because you could see everything from the top), the best tide pool, and the spot on the western beach where dolphins sometimes appeared at dawn."},
            {"page_number": 6, "operation": "CREATE", "text": "Then came the letter Isla had been secretly hoping for. 'I have been building something,' Leo wrote. 'I am not very good at building but I have been practising. I think it might be ready in two weeks. I am going to sail to your island. I hope that is all right. Pinchy says it is a terrible idea because of the open water but Pinchy is a crab and therefore cautious by nature. Please write back and tell me where to land.' Isla wrote back immediately: 'The western beach. The dolphins will know you're a friend.'"},
            {"page_number": 7, "operation": "CREATE", "text": "The two weeks felt like two years. Isla cleaned her hut thoroughly. She stocked up on coconuts and dried fish. She practised conversations in her head and then felt embarrassed about practising conversations in her head. On the morning of the fourteenth day she climbed the Observatory tree before sunrise and sat there watching the horizon. The sun came up. The sea glittered. Nothing. Then, just after breakfast, a small shape appeared on the water — a raft with a patched sail, moving steadily westward."},
            {"page_number": 8, "operation": "CREATE", "text": "The raft bumped onto the western beach and a boy climbed out — slightly sunburned, slightly damp, carrying a battered bag and what appeared to be a very grumpy crab in a small jar of seawater. Isla stood on the beach and they looked at each other. They had written hundreds of words to each other. Now neither of them could think of a single one. Then they both started talking at the same time, and then both stopped at the same time, and then both laughed at exactly the same moment — the same laugh, it turned out, surprised and delighted."},
            {"page_number": 9, "operation": "CREATE", "text": "Leo stayed for a week. They climbed the Observatory tree together and saw four other islands from the top. They snorkelled over the reef with the red coral and Leo drew a new map with everything in it. Pinchy escaped from his jar and spent three days hiding behind the tide pool rocks before consenting to come back. They ate coconut and dried fish and talked from morning until the stars came out, catching up on all the conversations you can't have in a letter, discovering that a friend you have only written to is exactly as real as a friend you can stand next to."},
            {"page_number": 10, "operation": "CREATE", "text": "When Leo sailed back to his own island, he left the map he had drawn on the wall of Isla's hut, next to the one she had drawn of his. Two islands. Two maps. A channel of sea between them that already felt like a road. That evening Isla sat on the western beach and a bottle came in on the tide — it must have been thrown just before he set sail. Inside was a note: 'Same time next month? I'll bring better provisions. Pinchy says absolutely not but we both know he doesn't mean it.' Isla laughed. She was already composing her reply. THE END"},
        ]
    },
    {
        "title": "Galaxy Racers",
        "book_id": "770f4835-06db-44cd-9fcf-2c29d979fa22",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "c4aac66a-5989-4879-b445-c1aa38f1915e", "text": "Every year the biggest event in the entire galaxy was the Star Trail Race — a wild and brilliant zoom through asteroid fields, past glowing nebulas, and twice around the rings of Saturn. The best pilots from every planet entered, in ships of every shape and size and colour, and the winner received a golden comet trophy and their name engraved on the Wall of Champions on the moon of Arcturus. This year, eleven-year-old Zara was finally old enough to enter. She had been training for three years."},
            {"page_number": 2, "operation": "UPDATE", "page_id": "6b325926-06f8-432a-a4ad-f16a494c902c", "text": "Zara's ship, the Silver Spark, was small and a little dented and had been repaired so many times that different panels were painted slightly different shades of silver. She had tuned the engine herself, learning from her dad who had raced for twenty years before his knees gave out from all the G-forces. 'Speed isn't everything,' he always said. 'Smart flying wins races.' Zara had written this on a sticker above her controls where she could see it always. She looked at it now as the other ships lined up around her at the starting grid."},
            {"page_number": 3, "operation": "UPDATE", "page_id": "88d93821-9100-4aa5-bc1f-5712924a3e98", "text": "At the starting line, Zara assessed her competition. Blaze, the defending champion, sat in his enormous red rocket that cost more than some small planets. Rex, loud and confident, had twin turbo boosters that could push him to extraordinary speeds in a straight line. The twins Mia and Moa flew in perfect practised formation and had never once been separated on a race course. Everyone in the crowd had their name but not Zara's. The countdown began. Five. Four. Three. Two. One. ZOOM. The sky exploded with ships."},
            {"page_number": 4, "operation": "CREATE", "text": "Blaze immediately shot to the front, his enormous engines leaving a blazing red trail across the stars. Rex was right behind him, boosters screaming. The twins threaded through traffic with practised elegance. Zara let them all go. She had studied the course for two years and she knew something they didn't: the first asteroid field had a narrow corridor on the lower route that nobody ever took because it looked too tight. It wasn't. She dropped her nose and cut through it at full speed, saving forty-seven seconds."},
            {"page_number": 5, "operation": "CREATE", "text": "By the time they reached the nebula section, Zara had moved up to eighth place just by flying smart. The nebula was the most beautiful part of the race — clouds of gas in pink and gold and violet, so thick you navigated by instruments alone. Zara had memorised the instrument readings she needed. Some pilots slowed down in the nebula, frightened by the reduced visibility. Zara did not slow down. She came out of the nebula in fourth place and heard a surprised cheer crackle through her radio from someone watching at home."},
            {"page_number": 6, "operation": "CREATE", "text": "Saturn's rings were next — the most dangerous section. The rings were made of ice and rock, some pieces the size of a fist and some the size of a house, and they moved constantly. You could not plan your route through the rings. You had to read them as you went, making split-second decisions, trusting your instincts. This was where Zara came alive. Her hands moved across the controls with a fluency that felt like music. She wove through the rings, under a tumbling boulder, over a flat sheet of ice, tight left past a spinning cluster, and out the other side in second place."},
            {"page_number": 7, "operation": "CREATE", "text": "Blaze was first, just ahead of her. He had been in first place for the whole race and his confidence showed in the way he flew — fast but relaxed, certain of his victory. He hadn't noticed Zara moving up through the field because she had done it quietly and cleverly. Now she was right behind him with one section left: the long straight home past the moons of Jupiter, where engines and fuel management determined everything. Zara checked her fuel gauge. She had saved more than anyone. She smiled."},
            {"page_number": 8, "operation": "CREATE", "text": "She opened the Silver Spark's engine to full for the first time in the entire race. The little ship surged forward with a sound like thunder. Blaze heard her coming and pushed his own throttle further — but he had been running at full power all race and had less in reserve. Zara pulled alongside him. He looked across at her — this small dented silver ship, this girl nobody had heard of — and she could see even through his visor that he was surprised. She pulled ahead. One kilometre from the finish she crossed into the lead."},
            {"page_number": 9, "operation": "CREATE", "text": "The Silver Spark crossed the finish line first. For a moment Zara just sat there in the sudden quiet of the cockpit, hands still on the controls, heart hammering. Then the radio exploded with voices — the race commentator, her dad, her team, the crowd. She pulled off her helmet and looked out at the stars through the porthole — the same stars she had looked at from her bedroom window and promised herself she would one day race through. She had done it. She pressed her hand against the sticker above the controls."},
            {"page_number": 10, "operation": "CREATE", "text": "On the podium, they gave her the golden comet trophy. It was heavier than she expected and it caught the light beautifully. Blaze stood next to her, and after a moment he held out his hand. She shook it. 'Good race,' he said, and she could tell he meant it. Her dad found her afterwards in the crowd and hugged her so hard her feet left the ground. 'Smart flying,' he said into her hair. 'Smart flying wins races.' The Wall of Champions on the moon of Arcturus had a new name on it. It was hers. THE END"},
        ]
    },
    {
        "title": "Ocean Wonders",
        "book_id": "da7a01a5-cd8f-4aed-a0ad-4e5d667355e7",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "2bc8ba13-2800-4508-abdd-4feeaafdff69", "text": "Mara had never seen the ocean before. When the car finally came over the hill and the sea appeared — enormous and glittering and stretching to the horizon in every direction — she pressed her face so hard against the window her nose went flat. Her family laughed. She didn't care. The sea was blue-green and alive and bigger than she had imagined anything could be, and the moment the car stopped she had her door open and was running down to the water's edge, the sand shifting under her feet in a way that was completely new."},
            {"page_number": 2, "operation": "UPDATE", "page_id": "c31af39a-a89e-4873-ac35-c3fbfbcbf570", "text": "She stood at the water's edge with her toes in the cold foam and her mouth wide open. A wave rushed up around her ankles — cold, alive, pulling back with a hissing sound — and she laughed so hard her belly ached. 'Go on,' said her mum behind her. Mara went. She waded in up to her knees, then her waist, then her shoulders, and then a wave lifted her entirely off the sand and she was swimming, actually swimming in the actual sea, and it was the best feeling she had ever had in her whole ten years of living."},
            {"page_number": 3, "operation": "UPDATE", "page_id": "337a34d7-c983-4680-9e1c-97bed7e2e4dd", "text": "With her little net and bucket, Mara explored the rock pools at the far end of the beach. Inside each one was a whole tiny world — spiky sea urchins sitting like purple stars, hermit crabs dragging their borrowed shells across the rock, anemones that looked exactly like flowers until you touched them and they closed up in a slow surprised blink. A small orange starfish sat perfectly still on a rock. 'Hello,' Mara whispered. She felt certain it winked at her. Her dad said starfish don't wink. Mara was not entirely convinced."},
            {"page_number": 4, "operation": "CREATE", "text": "Her dad knew a lot about the sea. He had grown up near the coast and spent his whole childhood in it. He showed Mara how to identify the different types of seaweed — the flat green sheets, the long brown ribbons, the tiny bubbled strings that popped satisfyingly when you squeezed them. He showed her how the tide had left a line of treasures along the beach: shells, pebbles worn smooth by years of tumbling in the waves, a single perfect sea glass, frosted green, with all its sharp edges softened away. He let her keep the sea glass."},
            {"page_number": 5, "operation": "CREATE", "text": "In the afternoon they hired a small rowing boat and went out past the breakers into calmer water. Here the sea was a different colour — deeper, darker, a true blue-green over the sandy bottom. Mara leaned over the side and looked down. She could see for what felt like miles: sunlight making shifting patterns on the sand, a shoal of small silver fish moving as a single shimmering shape, a long ribbon of dark seagrass swaying in a current she couldn't feel from the surface. The sea had a whole sky of its own, going down instead of up."},
            {"page_number": 6, "operation": "CREATE", "text": "Just before they turned back, a seal appeared. It surfaced ten metres from the boat, regarded them with large liquid eyes, then dove again in one smooth arc. Mara gripped the side of the boat. 'Will it come back?' she whispered. 'Maybe,' said her dad. They waited. Two minutes later it surfaced on the other side — closer this time, curious. Mara and the seal looked at each other for a long still moment. Then it dove again and was gone. Mara breathed out slowly. She felt as though something important had just happened, though she couldn't have said what."},
            {"page_number": 7, "operation": "CREATE", "text": "That evening they ate fish and chips on the harbour wall, watching the fishing boats come in. The chips were hot and salty and the portions were enormous. Mara ate everything. The sky turned pink and orange over the water. The boats rocked gently against their ropes, their hulls knocking against the wooden pier in a slow rhythm like a heartbeat. Mara listened. The harbour, she thought, had a sound like breathing — the water going in and out, in and out, the same rhythm it had kept for thousands of years while different people sat on different harbour walls and ate their chips and watched."},
            {"page_number": 8, "operation": "CREATE", "text": "Before bed, Mara sat on the floor of the cottage with her bucket of collected shells and sorted them. She had twelve different kinds — she counted carefully and looked them up in the guide from the gift shop. Scallops with their fan shape. Whelks in their spiral. Mussels with their dark blue sheen. One perfect razor clam. One she couldn't identify at all, which her dad said was the best kind. She arranged them on the windowsill in a row where the morning light would hit them, and went to sleep listening to the sound of the sea."},
            {"page_number": 9, "operation": "CREATE", "text": "On the last morning, Mara got up before everyone else and walked down to the beach alone. The tide was out further than she had seen it, revealing a wide stretch of wet sand that the sea had left behind, full of its own patterns — ripples and pools and the trails of things that had moved across it in the night. The sky was pale and the sea was quiet and she had the whole beach entirely to herself. She walked to the water's edge and stood there, looking at the horizon, saying goodbye in the way you say goodbye to something enormous — not out loud, just inwardly, with your whole chest."},
            {"page_number": 10, "operation": "CREATE", "text": "In the car on the way home, Mara held the green sea glass in her fist and looked out at the fields rolling past and thought about everything she had seen. The seal's eyes. The starfish. The world under the rowing boat. The way a wave felt when it lifted you. She would come back, she promised herself. She would come back every year until she knew every shell and every tide pattern and where the seals liked to surface and which rock pool held the most interesting things. There was simply far too much wonder to see it all in one visit. THE END"},
        ]
    },
    {
        "title": "Princess and the Enchanted Forest",
        "book_id": "1cb453f2-65f3-40c5-ab32-d3d96fb17f80",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "a1bdaab9-2132-4f6b-ade1-c6994ac6f6ba", "text": "Princess Rowan was not the sort of princess who sat around waiting to be rescued. She preferred muddy boots, tangled hair, and the kind of adventure you had to climb over something to reach. Her mother said she was spirited. Her father said she was a handful. Her riding instructor said she was extraordinary. Rowan said nothing and went on having adventures. On the morning of this particular story, she slipped out of the palace before breakfast, leaving a note that said simply BACK BEFORE LUNCH, and headed for the Enchanted Forest."},
            {"page_number": 2, "operation": "UPDATE", "page_id": "936c89cc-79da-4093-bf3e-9a64c46cc260", "text": "The Enchanted Forest was the one place everyone told Rowan never to go. This was, of course, part of its appeal. She had looked at it from the palace windows every day of her life — the dark line of trees at the edge of the kingdom, always slightly misty, always seeming to lean toward her slightly, as if leaning and looking back. The moment she stepped between the trees the whole forest shimmered gold, just for a moment, and the mist parted like a curtain being pulled aside. Something in the forest, she understood, had been waiting for her."},
            {"page_number": 3, "operation": "UPDATE", "page_id": "083bb2f9-e5ba-45c4-afa3-1481d997e0d7", "text": "Strange and wonderful things happened in the Enchanted Forest. Flowers turned their faces toward her as she passed. A fox with silver fur appeared on the path ahead — not running, just waiting — and when she followed it, it led her down a path that she was quite sure had not been there a moment before. The trees grew older and larger as she walked deeper, their roots rising from the ground in great arching curves. At the end of the path sat the oldest tree she had ever seen, its trunk so wide three people couldn't reach around it, with a hollow at its base sealed by a tiny door."},
            {"page_number": 4, "operation": "CREATE", "text": "The door was no bigger than Rowan's hand — made of bark and wound through with living vines, fitting so perfectly into the hollow that you'd miss it unless you were looking. A voice came from behind it: small and old and cautious, saying words she couldn't quite make out. Rowan crouched down and put her ear close. 'Only someone truly brave and truly kind can open this door,' the voice said. Rowan thought for a long moment. She had faced plenty of challenges that required bravery. The kindness part, she thought, was actually more important. She knocked very gently. 'Please may I come in? I would love to meet you.'"},
            {"page_number": 5, "operation": "CREATE", "text": "The door swung inward with a sound like a sigh. Inside, in a space that seemed larger than the hollow should allow, stood a whole village of woodland sprites — no taller than Rowan's thumb, with wings like dried leaves and eyes like polished acorns. There were hundreds of them. They had been trapped inside the tree for a hundred years by an enchantment that had simply been forgotten — not cast by an enemy, just the remnant of old protective magic that had outlasted its purpose and didn't know how to end. They stared at Rowan. She stared back. Then the eldest sprite, who had a white beard down to his knees, said: 'We hoped someone would come.'"},
            {"page_number": 6, "operation": "CREATE", "text": "Rowan helped them out one by one, which took a considerable time because there were a great many of them and they were all quite stiff from a hundred years of standing around inside a tree. She sat on the root with her legs crossed and held each one in her cupped palms and carried them to the edge of the hollow where they could stretch their wings in the proper air. The sprites shook their wings, blinked in the dappled forest light, and made small sounds of pure relief. The silver fox sat nearby and watched the whole operation with dignified approval."},
            {"page_number": 7, "operation": "CREATE", "text": "Once all the sprites were free, something extraordinary happened to the forest. It was as if it exhaled — a long slow breath through every leaf and root and branch. The mist that had hung over it for as long as anyone could remember thinned and dispersed. Sunlight came through in proper shafts, golden and warm. The trees seemed to stand differently, somehow — less hunched, more open. The eldest sprite told Rowan that the enchantment had been making the whole forest sad for a hundred years. 'We didn't know,' Rowan said. 'How could you?' said the sprite. 'You hadn't come yet.'"},
            {"page_number": 8, "operation": "CREATE", "text": "The sprites showed Rowan the hidden parts of the Enchanted Forest in return — the places that no human had seen in a century. A glade where every tree grew in a perfect spiral. A stream whose water was so clear it looked like glass, with fish that seemed to be made of light. A hill where the grass grew in a dozen shades of green, each shade corresponding to a different kind of luck. The eldest sprite told her the names of each thing in the old forest language, which sounded like wind in branches, and Rowan tried to remember all of it."},
            {"page_number": 9, "operation": "CREATE", "text": "All too soon, the light through the trees told her it was approaching lunch and she had made a promise. The sprites gathered to see her off. The eldest handed her a tiny acorn carved with a pattern she couldn't quite read. 'Come back,' he said. 'The forest will know you now.' Rowan closed her fingers around the acorn and looked back at the village of sprites settling happily into the spaces between the roots, rediscovering their home after a century. The silver fox appeared at her side and led her back to the path. She followed it out of the trees into the ordinary morning light."},
            {"page_number": 10, "operation": "CREATE", "text": "She arrived back at the palace exactly at lunch. Her boots were very muddy. Her hair was considerably more tangled than it had been. In her pocket was an acorn with a carved pattern and in her head was a forest language that sounded like wind. Her mother looked at her muddy state and sighed. Her father looked at her expression — that particular brightness in her eyes that meant something significant had happened — and said nothing, only smiled. Rowan sat down to lunch and thought about what she had learned: that sometimes the greatest magic is not what you find, but the act of knocking, gently and kindly, and asking to come in. THE END"},
        ]
    },
    {
        "title": "The Dinosaur Time Machine",
        "book_id": "2d44ad4f-61ce-439f-9fbf-f7bdc441ae59",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "74d00bca-94e7-4abe-892a-7a550c738947", "text": "Max loved dinosaurs with the kind of love that takes over an entire bedroom. Every wall was covered in posters. Every shelf held models. His bookcase was packed with field guides and encyclopaedias and two books he had read so many times the spines had given up. He knew the difference between a Brachiosaurus and a Brontosaurus and was very polite but firm when adults confused them. When he found the time machine in his grandfather's garage — a brass and copper cabinet covered in dials, with a sign reading TEMPORAL DISPLACEMENT DEVICE and a sticky note saying DO NOT TOUCH — he immediately touched it."},
            {"page_number": 2, "operation": "UPDATE", "page_id": "b022be41-b984-40b4-b383-04c80927ed1d", "text": "The machine rattled and flashed and made a sound like a very large clock being wound very quickly. When it stopped, Max stepped out of the garage into a world that was not the garage. The air was warm and wet and smelled of green growing things in enormous quantities. The sky was a different shade of blue — more vivid, somehow, as if the atmosphere were thicker. The ground was soft and covered in ferns that came up to his waist. And then he heard it: a sound like thunder that wasn't thunder, rhythmic and getting closer. The ground vibrated under his feet."},
            {"page_number": 3, "operation": "UPDATE", "page_id": "bf060e0a-5c0a-44b7-b6b8-cea1c6cd1765", "text": "The Triceratops emerged from the tree line twenty metres away. Three horns. Enormous frilled head. Eyes that were ancient and calm and slightly suspicious. It was the size of a large car and it was looking directly at Max. Max stood completely still, the way the books said to, and tried to make himself seem like a harmless plant. The Triceratops sniffed the air. Took two steps forward. Lowered its head. Then, apparently deciding Max was neither a threat nor anything interesting, went back to pulling up ferns with its beak. Max breathed out very, very slowly."},
            {"page_number": 4, "operation": "CREATE", "text": "He spent the morning observing from a respectful distance, notebook in hand, writing everything down with shaking hands that eventually steadied. The Triceratops was part of a herd — eight adults and three juveniles who moved together through the forest, communicating in low rumbles and occasional horn gestures that Max was fairly sure had meaning. The juveniles, he noticed, played. They shoved each other with their small horns and chased each other between the adults' legs. One of them kept wandering slightly too far and being herded back by a patient adult. Dinosaur parenting, Max thought, looked familiar."},
            {"page_number": 5, "operation": "CREATE", "text": "In the afternoon, he heard a different kind of sound — higher, shrieking, coming from somewhere through the trees. He moved carefully toward it and found a dry riverbed where a pair of Velociraptors were hunting. Everything the books had described was right: they were fast, they communicated with each other constantly, and they were terrifyingly intelligent. He watched one problem-solve its way around an obstacle with a patience and ingenuity that made his skin prickle. They were nothing like the movie versions. They were considerably more alarming. He stayed very still for a very long time."},
            {"page_number": 6, "operation": "CREATE", "text": "The baby Stegosaurus found him. He still didn't know how — he had been sitting quietly behind a tree — but suddenly it was there, sniffing his shoe with a thoughtful expression. It was about the size of a large dog, with plates along its back that were soft and slightly translucent, not yet fully grown. Its tail swayed slowly. It investigated his notebook. It investigated his other shoe. Then it sat down heavily on his foot, which he chose to interpret as affection. He named it Socrates, which he felt was a dignified name for a dignified creature."},
            {"page_number": 7, "operation": "CREATE", "text": "Socrates followed him for the rest of the day, which complicated his observations somewhat but made the day considerably better. Together they watched a herd of Ankylosaurus cross a river, slow and armoured and unstoppable. They witnessed a flock of Pterosaurs wheeling overhead in the orange late-afternoon sky, their calls carrying across the forest in long echoing notes. Once, in the distance, Max glimpsed something enormous moving through the trees — too large to be any of the species he'd seen so far, its footsteps shaking the ground even from half a kilometre away. He wrote T-REX? in his notebook with three question marks."},
            {"page_number": 8, "operation": "CREATE", "text": "As the sun began to lower and the shadows grew long across the fern floor, Max knew he would have to go back. The machine had given him a twelve-hour window — he'd read this on a small screen inside that he hadn't noticed at first. He looked at his notes: forty-seven pages, front and back, written in his smallest handwriting. He had seen things no human being alive had ever seen. He had sat next to a Stegosaurus. He had watched Velociraptors hunt. He had breathed the air of a world sixty-six million years in the past. His hands were still shaking slightly."},
            {"page_number": 9, "operation": "CREATE", "text": "He said goodbye to Socrates, which felt important even if Socrates didn't understand what goodbye meant. He patted the small dinosaur very gently on the warm side. Socrates swung its tail once, slowly, and turned back to the ferns. Max walked back to where he had landed, oriented himself carefully with his notebook, and placed his hand on the machine's return button. He looked back one last time at the prehistoric forest — the colours, the scale, the impossible aliveness of it all — and pressed the button."},
            {"page_number": 10, "operation": "CREATE", "text": "The garage reformed around him. His grandfather's toolboxes. The smell of oil and dust. Outside, through the small window, the ordinary sky of an ordinary Tuesday. Max sat down on the garage floor because his legs had decided they were done. He opened his notebook to the first page and looked at his first entry: 9:14am. Arrived. There is a Triceratops. He smiled so hard his face hurt. That evening he sat at his desk and began transferring his notes into his proper field journal, every detail, every observation, every moment. He had been the only human being to ever do this. He was going to do it justice. THE END"},
        ]
    },
    {
        "title": "The Haunted Treehouse",
        "book_id": "795336e6-3622-4342-968d-bec1098ebd1b",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "448ba3d5-ce6c-4b40-aac7-22dc266a04bb", "text": "Everyone in the neighbourhood said the old treehouse at the end of Bramble Lane was haunted. Lights flickered in it at night — bluish, uncertain lights that came and went without pattern. Strange sounds drifted from it on quiet evenings: creaks that might be the wood settling, or might not be. No child had climbed the rope ladder in at least ten years, which meant the rope ladder had developed a look of injury that probably didn't help. Everyone avoided it. Everyone except Priya, who had been staring at the treehouse from her bedroom window every morning for six months and had finally had enough of not knowing."},
            {"page_number": 2, "operation": "UPDATE", "page_id": "be64493c-a35e-4825-be6a-67597652b576", "text": "The rope ladder was shakier than it looked but held. The treehouse door was stiff and swollen in its frame but yielded to a firm push. Inside: dark, dusty, smelling of old wood and something faintly sweet. A stack of comic books in a corner, their covers faded. A broken telescope pointing at a gap in the boards. Cobwebs of impressive scale and ambition. And then — a sound. A rustling. A shifting of air. A glow in the far corner, pale blue and unsteady, accompanied by what Priya could only describe as the sound of someone trying very hard to be invisible and not quite managing it."},
            {"page_number": 3, "operation": "UPDATE", "page_id": "f817b4d4-087b-4fd7-9f73-035f9f00fb97", "text": "The ghost was smaller than expected. No bigger than a football, round and softly glowing, with a face that was currently arranged in an expression of deep embarrassment. 'I wasn't trying to frighten anyone,' it said, in a voice like a sound heard through water. 'I just didn't have anywhere else to go.' Priya sat down on the dusty floor and looked at it carefully. She had prepared herself for frightening. She had not prepared herself for apologetic. 'I'm Priya,' she said. 'I'm Pip,' said the ghost. 'I've been here for fifty years.' Priya looked around the treehouse. 'Tell me,' she said."},
            {"page_number": 4, "operation": "CREATE", "text": "Pip told her. He had been ten years old in 1974 when the treehouse was built by a boy named Thomas who had been his best friend. They had spent three summers up here, reading comics and using the telescope and making plans for adventures they were going to have. Then Thomas's family had moved away and Pip had gone home one afternoon and his family had moved away too, and somehow — this was the part he found hardest to explain — Pip had come back to the treehouse instead of following them. He had been here ever since. 'Waiting for Thomas?' Priya asked. Pip was quiet for a moment. 'Waiting for someone,' he said."},
            {"page_number": 5, "operation": "CREATE", "text": "Priya looked at the comic books. The top one had a date on it: July 1977. She looked at the telescope, pointed at its gap in the boards. She looked at Pip, floating quietly in his corner, glowing with the soft patience of someone who has been in one place for a very long time. 'I could fix the telescope,' she said. Pip's glow flickered, which she was learning to read as surprise. 'You can't fix it. It's broken.' 'I know how to fix telescopes,' said Priya, which was true — her dad had one and had taught her the mechanics of them when she was seven. 'Oh,' said Pip. Another flicker. 'All right then.'"},
            {"page_number": 6, "operation": "CREATE", "text": "She brought tools the next afternoon. The telescope needed a new lens mount, which she fashioned from a piece of metal pipe she found in her dad's garage, and a cleaning and realignment of the mirrors inside. Pip watched with intense interest, occasionally floating closer to look at what she was doing and occasionally drifting away again when he felt he was in the way. By the time she was done, the telescope pointed through the gap in the boards at a patch of evening sky in which two stars were already visible. Pip pressed his face — or the approximation of a face that he had — to the eyepiece. He went very still. 'I forgot,' he said softly. 'I forgot how many there were.'"},
            {"page_number": 7, "operation": "CREATE", "text": "She brought the comic books back the next week — found the same series at a second-hand book fair, the issues Pip didn't have from the years after Thomas left. She read them aloud because Pip's hands couldn't turn pages. He listened with the complete absorption of someone who had been waiting a very long time for a story to continue. Occasionally he would make a small sound of satisfaction when something he had been hoping would happen happened. Occasionally he would make a sound of outrage when it didn't. 'You're very emotionally invested for a ghost,' Priya told him. 'I've had a lot of time to develop feelings about comics,' Pip said with dignity."},
            {"page_number": 8, "operation": "CREATE", "text": "Word got out, because word always gets out. By the third week, Priya's friend Josie had climbed up to see for herself. Then Josie's brother. Then three other children from the road, who had been daring each other to approach the treehouse for years and now could do it because someone else had gone first. Pip was initially apprehensive. He had been a source of fear for so long that being a source of interest felt strange. But these children were curious and kind and they brought snacks and new comics and treated the treehouse with the respect it deserved, and Pip found, to his considerable surprise, that he liked them."},
            {"page_number": 9, "operation": "CREATE", "text": "They fixed the treehouse up together over several weekends. New boards where the old ones had rotted. A proper curtain for the window gap. A shelf for the comic collection. The rope ladder was replaced with a proper wooden ladder that Josie's dad helped build. Pip couldn't help with any of it physically, but he directed operations with enthusiasm and a photographic memory of where everything had originally been. 'The telescope goes on the left,' he would say. 'Thomas always kept it on the left.' They put it on the left. Some things, Priya understood, were worth doing exactly right."},
            {"page_number": 10, "operation": "CREATE", "text": "One evening in autumn, Priya climbed up to find Pip looking different — steadier, somehow. Less apologetically uncertain. More simply present. The treehouse was warm with the smell of old wood and the new curtain moved in a breeze through the repaired window. The comic collection was complete on its shelf. The telescope pointed at the stars. 'You're not really haunting it anymore, are you,' Priya said. It wasn't quite a question. Pip considered this. 'No,' he said. 'I think I'm just living here now.' Priya smiled. The treehouse had never, she thought, been haunted at all. It had just been waiting for the right people to fill it up again. THE END"},
        ]
    },
    {
        "title": "The Robot Who Wanted Friends",
        "book_id": "cb920fd3-c0bd-4be7-a40a-4ae2caeb8618",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "88501d03-ded8-4615-a8fd-6d68a72d9780", "text": "Cog had been built to sort nuts and bolts, and he was excellent at it. By size, by thread pitch, by material, by application — he could sort a thousand components in under four minutes and had never once made a mistake. The workshop was always tidy because of Cog. The shelves were always correctly stocked because of Cog. Every morning the owner arrived to find everything in order and every evening he left Cog to his sorting in the quiet and the dark. It was useful work. It was important work. It was also, Cog had concluded after careful consideration, extremely lonely work."},
            {"page_number": 2, "operation": "UPDATE", "page_id": "30adb7a5-6255-40aa-b039-48457ec800b5", "text": "Through the workshop window he could see the street. Children passed every morning on their way to school, and every afternoon on their way back, and sometimes on weekends in groups with no particular destination, ambling and talking and laughing at things he couldn't hear through the glass. He watched their body language the way he had been programmed to watch mechanical tolerances — with attention and interest and the desire to understand. He had identified seventeen distinct types of laughter. He had catalogued forty-two gestures that seemed to indicate friendship. He had never used any of them. He didn't know how to start."},
            {"page_number": 3, "operation": "UPDATE", "page_id": "b5b85478-7340-45ed-93cd-e0c6732dcb5f", "text": "The girl pressed her nose flat against the workshop window one Tuesday afternoon. She had bright curious eyes and a backpack covered in badges and she looked at Cog the way Cog looked at the street — with complete concentrated attention. Cog froze. Direct observation from a human was not something he had protocols for. He stood with a bolt in each hand and tried to decide what to do. The girl raised one hand and waved. Very slowly, uncertain, Cog raised one metal hand back. The girl's face did something extraordinary: it broke into the widest smile he had catalogued to date. She pointed at the door. She mouthed: Come out?"},
            {"page_number": 4, "operation": "CREATE", "text": "He put down the bolts. He had never left the workshop before during working hours. He walked to the door, which had a handle he had never used from this side, and opened it. The outside air was different from workshop air — warmer, fuller of information. The girl was standing right there. 'I'm Bea,' she said. Her voice was friendly and direct. 'I've been watching you sort things for three weeks. You're very fast.' Cog processed this. 'I know,' he said, because it was true. 'What else can you do?' Bea asked. Cog thought about this for longer than expected. He had never been asked before."},
            {"page_number": 5, "operation": "CREATE", "text": "They sat on the wall outside the workshop. Bea had a lot of questions, which Cog answered as accurately as he could. Yes, he could hear. Yes, he could see in colour. No, he didn't sleep — he had a low-power mode but it wasn't the same. Yes, he had opinions about things, though he was still developing what those were. Did he like things? He considered this. He liked when the bolts were sorted correctly. He liked the sound of rain on the workshop roof. He thought he might like talking to Bea, though he would need more data. 'That's basically how it works for me too,' said Bea. Cog found this helpful."},
            {"page_number": 6, "operation": "CREATE", "text": "Bea taught him hopscotch the following Saturday. His weight distribution made it technically challenging and he left noticeable impressions in the pavement where he landed, but the principle was sound and with modifications it worked. He was considerably better at the counting aspects than the jumping aspects. Bea was considerably better at the jumping aspects. They made, she said, a good team. Cog logged this: first use of the word 'team' in relation to himself. He noted it felt different from other information. It had a quality he didn't have a processing category for yet. He created one. He labelled it: significant."},
            {"page_number": 7, "operation": "CREATE", "text": "Bea introduced him to her friends one afternoon: three children from her class named Omar, Yuki, and Dev, who arrived in a group and regarded Cog with varying degrees of fascination. Omar asked him questions about his mechanics with great enthusiasm. Yuki was quieter but watched him with an attention that he recognised as the same kind he used himself. Dev immediately challenged him to a maths race, which Cog won comprehensively, and then challenged him to a drawing race, which Dev won comprehensively, and then they spent half an hour teaching each other and both improved, which Dev said was the whole point."},
            {"page_number": 8, "operation": "CREATE", "text": "The thing Cog was worst at, he discovered, was understanding emotions. He could identify them — he had excellent facial recognition and he had studied body language extensively — but understanding why they happened and what they required in response was more difficult. Bea was patient about explaining. 'When someone is sad,' she said, 'you don't need to fix it. Sometimes you just stay.' Cog processed this. It went against his core programming, which was oriented toward problem-solving. 'Just stay?' he said. 'Yes,' said Bea. 'That's usually enough.' He practised staying. It turned out to require considerable effort but produced good results."},
            {"page_number": 9, "operation": "CREATE", "text": "The workshop owner noticed the change in Cog. The sorting was still perfect — impeccable, as always — but Cog seemed different in a way that was hard to define. More present, perhaps. More oriented toward the window. He came in one evening to find Bea sitting on the workshop floor, doing homework, while Cog sorted next to her in companionable quiet. They weren't talking. They were just there, in the same space, being comfortable with each other. The workshop owner watched them for a moment and then quietly backed out and went home. Some things, he understood, didn't need interfering with."},
            {"page_number": 10, "operation": "CREATE", "text": "One afternoon Cog told Bea something he had calculated but not said out loud: that before she had pressed her nose against his window, he had been running at approximately forty percent of his potential. Not mechanically — his sorting was always perfect. But in every other way. 'You were lonely,' Bea said. 'Yes,' said Cog. 'That is the correct word.' Bea thought about this. 'I was a bit lonely too,' she said. 'Even with people around. It's different when you find the right one.' Cog filed this carefully. He was going to need a much larger category labelled significant. THE END"},
        ]
    },
    {
        "title": "The Superhero School",
        "book_id": "28e741d7-daf3-4c5c-b482-ac0f5dcde7be",
        "pages": [
            {"page_number": 1, "operation": "UPDATE", "page_id": "5e67f159-0c54-4ec5-ac37-b192137879db", "text": "On the first day at Heroic Heights School, the tradition was that every student received a cape. They came out of a wardrobe at the front of the hall one by one, drawn by some invisible process that matched cape to student: red for strength, blue for speed, gold for intelligence, silver for empathy, green for endurance. The hall rustled with the sound of children holding up their capes and feeling what they were. Nadia's was grey. She turned it over in her hands. It was a good quality grey — well made, neat stitching — but definitely, unmistakably, undeniably grey. 'Grey means undetermined,' said the teacher. 'Your power is still finding itself.'"},
            {"page_number": 2, "operation": "UPDATE", "page_id": "3b56089c-6fb3-41dd-9b7a-138b48534d84", "text": "In Powers Development class, they practised. Around Nadia, children were discovering abilities with expressions ranging from terrified to euphoric. A boy named Theo lifted his desk with one finger and then put it down very carefully and didn't touch anything for twenty minutes. A girl called Suki ran to the wall and back so fast she appeared twice simultaneously. A boy named Reed got the answer to every question before the teacher finished asking it. Nadia sat at her desk and tried very hard to do something — anything. She concentrated. She focused. She achieved mild transparency in her left hand, which was not nothing, technically, but felt like nothing."},
            {"page_number": 3, "operation": "UPDATE", "page_id": "1ed9b03f-ae66-4036-9c91-b9b7c39004ce", "text": "The kitten challenge was set by Ms Marvel on the third day. A kitten had climbed the school's tallest oak tree and was sitting on the highest branch making the particular sound that means both 'help me' and 'I am also enjoying this attention' at once. Ms Marvel looked at her class. 'Solve it,' she said. Theo tried to lift the tree. He lifted it four inches before deciding this was inadvisable. Suki ran up the trunk — impressive — but the kitten retreated further. Reed knew exactly what to do but couldn't execute it. Nadia went to the canteen, found sardines, opened the tin, held it up. The kitten descended with dignified speed."},
            {"page_number": 4, "operation": "CREATE", "text": "Nadia's cape shimmered at the edge of grey, the faintest silver beginning to show. Ms Marvel noticed but said nothing yet. In the classroom debrief, she asked each student what power they had used on the kitten problem. 'Strength,' said Theo. 'Speed,' said Suki. 'Analysis,' said Reed. Then she looked at Nadia. 'I just thought about what the kitten actually needed,' Nadia said. 'Rather than what I could do.' Ms Marvel wrote something on the board: PROBLEM DEFINITION. 'The most powerful skill in heroism,' she said, 'is understanding what problem you're actually solving before you try to solve it.'"},
            {"page_number": 5, "operation": "CREATE", "text": "Hero History classes were Nadia's favourite. They studied heroes throughout time — not the ones with the most impressive powers, but the ones who had made the most difference. She was particularly interested in those who had solved problems that everyone else was solving wrong. A water engineer who ended a drought not by making it rain but by redesigning how water was stored. A negotiator who ended a conflict not by overpowering either side but by finding the one thing they both actually needed. 'These people had grey capes,' Nadia said to Ms Marvel after class. 'Almost certainly,' Ms Marvel agreed."},
            {"page_number": 6, "operation": "CREATE", "text": "The academy's annual Challenges week came in October. Each student faced a series of problems designed to test their specific powers. The others had straightforward tests: lift this, run here, answer this. Nadia's tests were different. She was given situations — a team that wasn't working, a resource that wasn't being used well, a conflict that had no obvious solution — and asked to improve them. She approached each one the same way: first understand exactly what the problem was, then find the simplest intervention that changed it. She solved every one. Her cape turned noticeably silver by the end of day three."},
            {"page_number": 7, "operation": "CREATE", "text": "Theo asked her to help him with something. He was enormously strong but kept accidentally breaking things — doors, chairs, equipment — because he didn't know his own power yet. 'What am I doing wrong?' he asked. Nadia watched him try to open a door and immediately saw it: he was applying strength uniformly instead of calibrating it. 'You're solving every problem at maximum,' she said. 'Try ten percent first and scale up.' Theo tried it. The door opened intact. He stared at his hands. 'How did you see that?' he asked. Nadia shrugged. 'I watched what you were actually doing.' It was the most useful thing anyone had said to him since he'd arrived."},
            {"page_number": 8, "operation": "CREATE", "text": "Word spread through Heroic Heights that Nadia could help you understand your own power better than you could yourself. Students started finding her at lunch, at break, in the corridors between classes. She never told anyone what to do — she just asked questions, the right questions, until they saw it themselves. Ms Marvel watched this from a distance with quiet satisfaction. She had taught at Heroic Heights for twenty years and had seen many impressive powers. She had rarely seen one this rare. She updated Nadia's file with a single new entry under power classification: Insight."},
            {"page_number": 9, "operation": "CREATE", "text": "Near the end of term, Heroic Heights faced a real problem. A section of the school's foundations had developed a crack that the structural engineer said was serious. The students were given the challenge for real: solve this problem before the affected wing had to close. Teams formed — strength teams to shore up walls, speed teams to evacuate equipment, intelligence teams to model solutions. Nadia was given team leadership, which surprised her. She sat everyone down and spent twenty minutes just asking questions before she let anyone do anything. When they finally acted, they acted correctly, and the problem took four hours instead of the estimated two days."},
            {"page_number": 10, "operation": "CREATE", "text": "On the last day of term, capes were reassessed. One by one, students went to the front and their capes shimmered into whatever they had become. Theo's deepened red. Suki's blazed blue. Reed's shone gold. When Nadia stood at the front, her cape blazed so brilliantly silver that students shielded their eyes. It was not a colour she had seen on any cape before. 'Silver and grey,' said Ms Marvel quietly, 'make platinum.' She held up the assembly register. On the first page, in the column for most valuable students: Nadia's name, at the top, with a star. Not because she was the strongest or the fastest or the cleverest. Because she helped everyone else be better. THE END"},
        ]
    },
]


async def run_import(dry_run=True):
    """Run the import with UPDATE and CREATE operations"""
    
    mongo_url = os.environ.get('MONGO_URL')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    mode = "DRY RUN" if dry_run else "APPLYING"
    print(f"\n{'='*60}")
    print(f" {mode} - Batch 3A Revised Import")
    print(f"{'='*60}")
    
    total_updates = 0
    total_creates = 0
    update_errors = 0
    create_ready = 0
    
    for book_data in BOOKS_DATA:
        book_title = book_data["title"]
        book_id = book_data["book_id"]
        
        print(f"\n📚 {book_title}")
        print(f"   Book ID: {book_id}")
        
        # Verify book exists
        book = await db.books.find_one({"id": book_id})
        if not book:
            print(f"   ❌ ERROR: Book not found in database!")
            continue
        
        updates_in_book = 0
        creates_in_book = 0
        
        for page_data in book_data["pages"]:
            page_num = page_data["page_number"]
            operation = page_data["operation"]
            text = page_data["text"]
            
            if operation == "UPDATE":
                page_id = page_data["page_id"]
                # Verify page exists
                existing_page = await db.pages.find_one({"id": page_id})
                if existing_page:
                    current_len = len(existing_page.get("text_content", ""))
                    new_len = len(text)
                    if dry_run:
                        print(f"   ✅ Page {page_num} UPDATE: {page_id[:8]}... ({current_len} → {new_len} chars)")
                    else:
                        # Actually update
                        await db.pages.update_one(
                            {"id": page_id},
                            {"$set": {"text_content": text}}
                        )
                        print(f"   ✅ Page {page_num} UPDATED: {current_len} → {new_len} chars")
                    updates_in_book += 1
                    total_updates += 1
                else:
                    print(f"   ❌ Page {page_num} UPDATE FAILED: Page ID {page_id} not found!")
                    update_errors += 1
                    
            elif operation == "CREATE":
                if dry_run:
                    print(f"   🆕 Page {page_num} CREATE: {len(text)} chars")
                    creates_in_book += 1
                    create_ready += 1
                else:
                    # Create new page
                    new_page_id = str(uuid.uuid4())
                    new_page = {
                        "id": new_page_id,
                        "book_id": book_id,
                        "page_number": page_num,
                        "text_content": text,
                        "image_url": None,
                        "audio_url": None,
                        "created_at": datetime.now(timezone.utc).isoformat(),
                        "updated_at": datetime.now(timezone.utc).isoformat()
                    }
                    await db.pages.insert_one(new_page)
                    
                    # Also add to book's embedded pages array
                    await db.books.update_one(
                        {"id": book_id},
                        {"$push": {"pages": {
                            "id": new_page_id,
                            "page_number": page_num,
                            "text_content": text,
                            "image_url": None,
                            "audio_url": None
                        }}}
                    )
                    print(f"   🆕 Page {page_num} CREATED: {new_page_id[:8]}... ({len(text)} chars)")
                    creates_in_book += 1
                    total_creates += 1
        
        print(f"   Summary: {updates_in_book} updates, {creates_in_book} creates")
    
    print(f"\n{'='*60}")
    print(f" {mode} SUMMARY")
    print(f"{'='*60}")
    
    if dry_run:
        print(f" ✅ UPDATE operations verified: {total_updates} pages")
        print(f" 🆕 CREATE operations ready: {create_ready} pages")
        print(f" ❌ Errors: {update_errors}")
        print(f"\n Total pages to process: {total_updates + create_ready}")
        if update_errors == 0:
            print(f"\n ✅ All {total_updates} Page IDs matched!")
            print(f" ✅ All {create_ready} new pages ready to create!")
    else:
        print(f" ✅ Pages UPDATED: {total_updates}")
        print(f" 🆕 Pages CREATED: {total_creates}")
        print(f" ❌ Errors: {update_errors}")
        print(f"\n Total pages processed: {total_updates + total_creates}")
    
    print(f"{'='*60}\n")
    
    client.close()
    return update_errors == 0


if __name__ == "__main__":
    dry_run = "--apply" not in sys.argv
    asyncio.run(run_import(dry_run))
