#!/usr/bin/env python3
"""
Batch 3C Import - 13 Valid Books (130 pages)
Excludes: The Emotion Squad, The Monster Under My Bed (invalid IDs)
"""

import asyncio
import os
import uuid
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv
load_dotenv('/app/backend/.env')

BOOKS_DATA = {
    "875cb08c-5634-4304-ae34-07fb0c446afe": {
        "title": "The Arctic Expedition",
        "pages": [
            {"page_number": 1, "text": "The Arctic received Jonas in the way that very large places receive small things: without acknowledgement, without adjustment, continuing whatever it was already doing regardless of his arrival. He stood on the sea ice on the first morning and looked in every direction and saw white — white ground, white horizon, white sky above — with the occasional interruption of pale blue where pressure had fractured and refrozen the ice into ridges. His breath made clouds. The cold was not unpleasant so much as absolute: a fact of the air, total and neutral, treating him and the ice and the distant horizon all the same. He had been told it was beautiful. This was insufficient."},
            {"page_number": 2, "text": "His mother, Dr Sigrid, had been working in Arctic climate research for fifteen years. She had brought him on this expedition partly because he was eleven and old enough and partly because she had been explaining her work to him for five years and had decided he was ready to see it. The research station was small — six scientists, a cook, and now Jonas — on the sea ice north of Svalbard, accessible only by small plane and, for a few months a year, by ship. The station had been measuring the same data points for twenty years. The data told a story. Jonas had read summaries of it. Being here was different from reading summaries."},
            {"page_number": 3, "text": "His job was to help his mother, which meant carrying equipment and writing measurements in the logbook and not falling into any of the cracks in the ice, which were called leads and which his mother had spent considerable time telling him about before they arrived. The ice was not flat. It moved — not visibly, not while you watched, but measurably, over time, drifting on the ocean below it, compressing and separating, thickening and thinning with the seasons. Every measurement his mother took was a data point in a record that stretched back two decades. He understood, writing the numbers, that he was writing sentences in a story that mattered enormously."},
            {"page_number": 4, "text": "The Arctic fox found them on the third day. It appeared at the edge of the station's perimeter with the casual confidence of an animal that owns everywhere it stands, white-coated and bright-eyed, and sat down at a polite distance to observe operations. Jonas sat down at an equally polite distance from it and they regarded each other with mutual interest. The fox had no fear of humans — the station had been here long enough that the local animals treated it as a feature of the landscape — but it maintained its dignified autonomy, coming close enough to satisfy its curiosity and no closer. It visited every afternoon for the rest of their stay."},
            {"page_number": 5, "text": "The polar bear tracks were found on the fifth morning — a mother and two cubs, the prints pressed deep and clear into a patch of softer snow between two pressure ridges. Jonas's mother photographed them and took measurements: the width of the forepaw, the length of the stride, the weight distribution visible in the depth of each print. The bears were somewhere close — the tracks were hours old at most. Jonas stood next to the prints and looked at the white landscape around him, trying to imagine the bears moving through it, invisible in their white coats, going about the urgent business of their lives."},
            {"page_number": 6, "text": "She talked to him about the ice as they worked — not lecturing, just explaining what she was seeing in the way someone explains things they love to someone they trust. The ice had memory, she said. It recorded conditions in its layers — temperature, precipitation, atmospheric composition — the way tree rings recorded growing seasons. A core drilled from deep ice could tell you what the air was like thousands of years ago. She had drilled cores that contained air bubbles from before humans existed in significant numbers. She had measured what was in those bubbles. She knew what the atmosphere had been and what it was now. The difference was the story she spent her life telling."},
            {"page_number": 7, "text": "The Northern Lights came on the seventh night. Jonas was outside for what his mother called star time — the hour before bed when he was allowed to sit outside alone if he was properly dressed and stayed within the station's marked perimeter. He was watching a particularly bright star in the north when the light began: a faint green shimmer at the horizon, barely distinguishable from the sky. Then it strengthened, and broadened, and rose — green deepening to blue-green at the bottom, fading to violet at the top, curtains of light folding and refolding across the sky in slow waves that corresponded to nothing he had ever seen before. He sat completely still."},
            {"page_number": 8, "text": "He understood, technically, what caused it — solar particles exciting atmospheric molecules, the different colours corresponding to different gases at different altitudes. His mother had explained this. Understanding the mechanism did nothing to reduce the experience of it. The lights moved in patterns that seemed almost intentional, though they weren't, that seemed almost musical, though they made no sound, that were simultaneously random and structured in the way that very large natural phenomena always are. He sat under them for forty-five minutes, which was longer than he was supposed to stay out alone, and his mother came and sat beside him without saying anything about the time."},
            {"page_number": 9, "text": "They found the bears on the penultimate morning. A lead had opened overnight — a channel of dark water cutting through the ice — and the mother bear was hunting at its edge, moving with the patient focused attention of something that knows exactly what it's doing. The cubs were nearby, practicing: small clumsy versions of the same careful stalking, occasionally distracted by each other. Jonas and his mother watched from the station with binoculars, not approaching. The mother bear caught a seal with a speed that was shocking after so much patient stillness. The cubs came running. Jonas wrote in his notebook: the patience before the speed. Have to remember both."},
            {"page_number": 10, "text": "On the last day he walked the measurement route with his mother one final time, helping her record the data that would become part of the twenty-year record. He wrote the numbers in the logbook carefully, in his neatest handwriting, because they mattered and because neatness was a form of respect for something important. At the last measurement point his mother stood for a moment looking at the ice, which looked the same as it always looked — white, vast, indifferent — but which she could read as easily as he could read a page. 'It's changing,' she said, not to him exactly, just out loud. He stood beside her and looked at the ice and thought about data points and sentences and stories that needed telling. 'I know,' he said. THE END"},
        ]
    },
    "b5cf1707-7930-4e72-a01c-8d21d052b693": {
        "title": "The Burping Dragon",
        "pages": [
            {"page_number": 1, "text": "Gerald had known since he was a hatchling that something was different about him. All the other young dragons in his clutch had produced their first flame at six weeks, small and uncertain but unmistakably fire. Gerald, at six weeks, had produced a noise. It was loud, resonant, impressively prolonged, and smelled powerfully of the particular vegetables he had eaten that morning. His parents had been supportive. His siblings had been less so. The elder dragons who assessed new hatchlings for ability wrote in their records: 'Gerald — fire production atypical. Reassess at six months.' At six months the reassessment had produced a larger and louder version of the same result."},
            {"page_number": 2, "text": "He had tried everything recommended for dragons with fire difficulties: breathing exercises, dietary adjustments, meditation, a three-week course with a specialist who had successfully retrained seventeen dragons with production problems. The specialist's notes on Gerald said: 'This is not a production problem. The mechanism appears fully functional. The output is simply different from standard. I have not previously encountered this.' Gerald had asked if 'different from standard' was a problem. The specialist had taken a very long time to answer. 'In dragon terms,' she had said carefully, 'it is unusual. In other terms, I genuinely cannot say.'"},
            {"page_number": 3, "text": "He settled into life in the valley with the philosophical acceptance of someone who has been unusual for long enough that it no longer surprises them. He was liked — genuinely, not with the forced warmth that people extend to those they feel sorry for, but because he was good company, an excellent listener, and knew an impressive number of things about geology, which he had studied extensively during the years when he was trying not to think about his fire situation. He kept his cave tidy. He maintained good relations with the neighbouring woodland. He occasionally, accidentally, produced his special noise at social gatherings, which cleared the area efficiently."},
            {"page_number": 4, "text": "The circus arrived in the nearest town in midsummer, and Gerald heard about it from a family of travelling merchants who passed through the valley. Brockett's Magnificent Travelling Show, they said, had acts from across the continent — acrobats, illusionists, trained animals, a woman who juggled fire (which Gerald considered somewhat pointed given his personal situation). They also mentioned, in passing, that the ringmaster had heard rumours of a dragon in the valley and had sent a message enquiring whether said dragon would be interested in discussing a professional opportunity. Gerald had been intending to say no. Then the merchants left and the valley was very quiet."},
            {"page_number": 5, "text": "Brockett was a large man with a magnificent moustache and the particular energy of someone who had spent forty years in show business and retained his enthusiasm through sheer force of will. He met Gerald at the valley entrance with no apparent concern about being in close proximity to a dragon — Gerald suspected he had met things considerably more surprising in his career — and outlined his proposal with the directness of someone who had given many pitches and had no time for preamble. 'A burping dragon,' he said. 'Unprecedented. The sound alone would be worth the ticket. The smell is a bonus. The small purple flame would bring the house down.' Gerald said he would think about it."},
            {"page_number": 6, "text": "He thought about it for three days, which was longer than he had thought he would need, partly because he kept coming back to the same question: was this dignified? He consulted the oldest dragon in the region, a vast and ancient creature who had been in the mountains for four centuries and who had an answer for most things. The ancient dragon thought about it for a day and then said: 'Dignity is earned by doing what you do with care and commitment, not by what you do. The question is whether you can do this with care and commitment.' Gerald thought about this for another day. Then he went to see Brockett."},
            {"page_number": 7, "text": "The first performance was in Brockett's largest tent, with an audience of two hundred people who had no idea what to expect. Gerald stood in the ring — enormous and rust-coloured in the spotlight — and looked at the rows of faces looking back at him. He took a breath. He thought, as his specialist had taught him, about the correct vegetables. He focused on the particular combination of root and leaf that produced the most resonant result. He breathed in. He breathed out. The resulting noise filled the tent, bounced off the canvas walls, rattled the pole supports, and concluded with the small purple flame that he still considered his least impressive feature. The silence lasted exactly two seconds. Then the tent erupted."},
            {"page_number": 8, "text": "The laughter was different from what he had experienced before — not the uncomfortable suppressed laughter of someone being polite about an embarrassing situation, but full, open, helpless laughter, the kind that people produce when something has surprised them into joy. Children were leaning on each other. Adults were wiping their eyes. Someone in the back row had fallen off their bench. Gerald stood in the ring and looked at two hundred people laughing with genuine abandon and felt something shift in his chest that he hadn't expected and couldn't immediately name."},
            {"page_number": 9, "text": "He performed twelve nights in that town and then the show moved on and he went with it. Every night was different — different audiences, different towns, different responses to the same performance — but the core of it was always the same: the preparation, the breath, the noise, the laughter, the small purple flame, the applause. He added things over time: a pause before the flame that built anticipation, a variation in pitch that he discovered he could control more than he'd thought, a theatrical expression of surprise at his own output that produced a second wave of laughter just when the first was subsiding. He was, it turned out, a natural performer."},
            {"page_number": 10, "text": "He stayed with Brockett's show for ten years, which in dragon terms was a modest commitment but in human terms was a significant career. When he finally returned to his valley, it was to find that his reputation had preceded him — the story of the Burping Dragon had spread, as good stories do, further than he had travelled. Young dragons came to ask his advice about unusual abilities. He told them the same thing each time: find somewhere that needs what you have, do it with care and commitment, and keep your cave tidy. The last piece of advice, he acknowledged, was less essential than the first two, but he felt strongly about it. THE END"},
        ]
    },
    "efdc724b-18b0-4901-a22f-e211836d76c2": {
        "title": "The Enchanted Carousel",
        "pages": [
            {"page_number": 1, "text": "The carousel had been at the edge of Ashford Park for longer than the oldest resident could remember, which was saying something since the oldest resident was ninety-four and had a very good memory. It had never been restored or repainted and yet it showed no sign of age: the horses gleamed, the gilded canopy kept its gold, the music — a waltz in a minor key, slightly melancholy, slightly joyful — played without any mechanism visible to account for it. The man who ran it, Mr Voss, had been there as long as the carousel itself, which made him either very old or something else entirely. Before each ride he always said the same thing: 'Hold on tight. Don't be afraid of where it takes you.'"},
            {"page_number": 2, "text": "Bea had ridden it every summer since she was small enough to need help climbing onto the horse. She was nine now, tall enough to mount herself, old enough to notice things she hadn't noticed before. Like the way Mr Voss watched the carousel after each group of riders with an expression that was not professional attention but something more personal — interest, or care, or both. Like the way the music seemed slightly different each time she rode, though she couldn't have said exactly how. Like the fact that last summer, at the end of her ride, she had seen — briefly, unmistakably — a landscape outside the carousel's rotation that was not the park. She had decided to ride again this summer and pay closer attention."},
            {"page_number": 3, "text": "The carousel began to turn. The park fell away — not dramatically, not with any special effect, simply began to occupy less of her attention than it should, the way a familiar room becomes difficult to recall clearly when you're concentrating on something else. The horse under her was warm in the way that wood in summer is warm, and then warmer, and then warm in a way that wood isn't. The music shifted register. The air smelled different — not the park's cut-grass-and-distant-chips smell, but something older: earth and rain and green growing things in greater quantities than Ashford Park had ever contained. Bea held on tight."},
            {"page_number": 4, "text": "The meadow was real. She knew it was real the way you know certain things — not because you can prove them but because every available sense confirms it simultaneously. The grass was long and dry and rustled against her legs. The sky was the precise blue of a summer afternoon that has been clear all day. The horse was gone and she was standing, which she did not remember doing. In the middle distance a line of trees marked the edge of a wood that she was quite certain had never been in any world she had previously inhabited. She stood still for a moment. Then she began to walk toward the trees."},
            {"page_number": 5, "text": "The wood was old and dense and the light inside it was green and filtered and moved with the trees. She walked for what felt like twenty minutes but might have been less — time inside the wood seemed approximate rather than precise. She found, at the wood's centre, a clearing where a spring emerged from a mossy rock and ran across white stones into shadow. The water was cold enough to ache and the clearest she had ever seen, and when she looked into the spring's pool she saw not a reflection of herself but of the meadow behind her, and in the meadow the horse was waiting. She turned around. It was."},
            {"page_number": 6, "text": "The horse led her to the shore — she hadn't expected a shore, hadn't known the landscape contained one, but it did, black sand and luminous water, the bioluminescence she had read about making the shallow waves glow cold blue-green in what she now realised was dusk. She waded in up to her knees. The light swirled around her feet in slow spirals. Something moved in the deeper water — large, graceful, visible as a shifting density of light rather than a shape. She watched it for a long time. It moved parallel to the shore, neither approaching nor retreating, as if keeping her company from a considerate distance. She raised one hand. The light-shape seemed, perhaps, to pause."},
            {"page_number": 7, "text": "She rode through a city made of glass that caught the remaining light and broke it into spectrum-colours across every surface. The people in it moved through streets that were transparent from below, so the whole city appeared to float. Nobody noticed her — or if they noticed her, they incorporated her into their world the way cities incorporate everything that passes through them: as a passing feature of no particular consequence. She saw a market selling things she had no names for. She saw a library whose shelves went up past any ceiling she could see. She saw a bridge over a canal that was somehow still and moving simultaneously. She tried to memorise all of it."},
            {"page_number": 8, "text": "The mountains were the last place. Stone and cold and the particular silence of high altitude, where the air is thin enough that sound carries differently and you can hear things at great distances with unusual clarity. She climbed — not struggling, not exactly, but aware of each step — until she reached a plateau where the view extended in every direction, the world spread out below in all its variety: the meadow, the wood, the shore, the glass city, the mountains themselves. All of it visible from here. All of it connected. She sat on the cold rock and looked at it and felt the particular vertigo of understanding that something is much larger than you had previously apprehended."},
            {"page_number": 9, "text": "The horse was there when she turned. It always was. She understood now that this was the carousel's logic: you were taken where you needed to go, and the horse returned when you had been there long enough. She mounted and they moved and the mountains dissolved and the park assembled itself around her in the way that dreams dissolve when you wake — all at once, the other world simply no longer present. Mr Voss helped her down. She stood for a moment in the ordinary afternoon light of the park, which was exactly as it had been. She looked at him. 'Where did I go?' she asked. 'Where you needed to,' he said. She looked at her hands. They were cold from the mountain air."},
            {"page_number": 10, "text": "She came back the following summer, and the one after that, and each time the carousel took her somewhere different — somewhere she would not have thought to go on her own, somewhere that left her with something she carried back and couldn't quite explain. Mr Voss was always there, and the music was always slightly different, and the horse was always warm under her hands. She stopped asking where she had been. She started asking, instead, what she had noticed. This turned out to be a better question. Over the years she filled a notebook with what she had seen: the meadow, the wood, the bioluminescent shore, the glass city, the mountains, and places after that she had no words for yet. She kept looking for the words. THE END"},
        ]
    },
    "40fde406-1757-4185-ab62-eb97264784e9": {
        "title": "The Feelings Garden",
        "pages": [
            {"page_number": 1, "text": "The garden existed in a place that was not quite a place — accessible through a gate in the back of an old library that should have opened into a car park but instead opened onto a path, and down the path to a garden enclosed by walls so old they had moss growing on the moss. The gardener was always there, always busy, wearing no particular expression that could be read as age. He had tended this garden for a very long time. The garden grew feelings, which was unusual but not — once you had spent time there — surprising. Things that grow need tending. Feelings, the gardener held, were no different."},
            {"page_number": 2, "text": "Iris found the gate at age ten by following a cat through the library that turned out not to be in the library's official animal policy. She stepped through the gate and stopped. The garden was large — much larger than the car park she had been expecting — and arranged in sections, each growing different flowers. She could identify some of them in the ordinary way: sunflowers, roses, violets, something white and delicate she had no name for. But they were also, simultaneously and without contradiction, other things. The sunflowers were radiantly happy. The roses were beautifully, dangerously angry. The violets were genuinely sad. She stood at the gate and felt it."},
            {"page_number": 3, "text": "The gardener found her standing at the gate and invited her in with the matter-of-fact welcome of someone who has been receiving visitors for a very long time and is neither surprised nor particularly making an occasion of it. He showed her around — this section for joy, this for sorrow, this for the complicated feelings that don't have simple names. He explained that the flowers grew from seeds that people brought, knowingly or not, and that tending them was important because feelings left untended could become overgrown or withered or invasive. She asked if she could help. He handed her a watering can."},
            {"page_number": 4, "text": "The watering can was heavier than it looked and the water inside it was not quite water — it had a quality of attention to it, a sense of being noticed. She watered the section the gardener indicated: a patch of small blue flowers that were, she understood without being told, loneliness. They were delicate and needed careful watering — too much and they would drown, too little and they would wither. She watered them with the focused care of someone who understood, instinctively, that this mattered. When she finished, the flowers seemed slightly less lonely. She wasn't sure how she knew this but she did."},
            {"page_number": 5, "text": "She came back every week after that, always on Saturday, always through the same gate. The gardener taught her the names of the feelings and the flowers that grew them and the particular care each one required. Anger needed pruning — left alone it would spread and choke other things. Fear needed sunlight and open space around it. Grief needed time and patience and the understanding that it would bloom in its own season. Love, surprisingly, was one of the hardiest plants in the garden — it could survive almost anything, though it grew best when tended regularly."},
            {"page_number": 6, "text": "The section she found hardest to tend was shame. The flowers there were small and grew close to the ground, almost hidden, and they flinched when she approached — actually flinched, pulling their petals inward. The gardener told her that shame was the most difficult feeling to care for because it didn't want to be seen, and yet being seen with kindness was exactly what it needed. She learned to approach it slowly, to sit near it without demanding anything, to let it unfurl in its own time. It took three months before the shame flowers would let her water them properly."},
            {"page_number": 7, "text": "She was twelve when she planted her first seed. She had been carrying something for weeks — a feeling she couldn't name, heavy and complicated, related to a friendship that had ended badly — and the gardener suggested she might want to give it somewhere to grow rather than carrying it around. She dug a small hole in a section reserved for new plantings, placed the feeling there (she didn't know how she did this, only that she did), and covered it with soil. A week later a small shoot emerged. She didn't know what it would become yet. Neither, apparently, did it."},
            {"page_number": 8, "text": "The plant that grew from her seed took six months to flower. When it did, it was unlike anything else in the garden — not a single feeling but several intertwined: loss and love and anger and something that might have been forgiveness, all growing from the same root system, all part of the same complicated thing. The gardener looked at it for a long time and then said: 'This is rare. Most people's complicated feelings stay complicated. Yours has found a way to be complicated and whole at the same time.' She wasn't sure if this was a compliment but she decided to take it as one."},
            {"page_number": 9, "text": "She was fourteen when she started bringing others to the garden. Friends who were struggling, who needed somewhere to put things they couldn't carry, who needed to see that feelings could be tended rather than just endured. The gardener welcomed each one with the same matter-of-fact hospitality. Some came once and never returned. Some came regularly. One stayed and became, like Iris, an apprentice — learning the names and the care and the patient work of helping things grow. The garden, she understood now, was not just a place. It was a practice."},
            {"page_number": 10, "text": "Years later, when asked what she did, she would say she was a gardener. This was true in multiple senses. She tended a garden that most people couldn't find, through a gate in the back of a library, where feelings grew in flowers and needed the same care as any living thing. She also tended the feelings of people who came to her — not fixing them, not solving them, just helping them find somewhere to grow, giving them water and light and time. The gardener had retired by then, or moved on, or whatever gardeners like him did. The garden was hers now. She opened the gate each morning and walked through. There was always work to do. THE END"},
        ]
    },
    "51c242bc-99a4-4456-b4dc-1821c2a75138": {
        "title": "The Giant's Gentle Heart",
        "pages": [
            {"page_number": 1, "text": "The giant lived alone on the far side of the mountain, which suited him because people were afraid of giants and he was tired of frightening them. His name was Moss — not because he was mossy, though he was, but because his mother had liked the word and had thought it suited someone who would grow slowly and stay where he was put. He had a cottage that he had built himself from stones as big as wagons, and a garden where the vegetables grew large because he sang to them, and a view of the valley below where people lived in houses that looked, from his height, like toys."},
            {"page_number": 2, "text": "He had not always lived alone. When he was younger — young for a giant, which meant about sixty — he had lived among people, helping with the tasks that giants were good at: moving boulders, building walls, lifting things that no normal person could lift. But even helping was frightening when you were four times the height of the tallest man, and eventually the fear had outweighed the usefulness, and he had retreated up the mountain where his size could not alarm anyone. He did not blame them for being afraid. He understood that fear was not always a choice."},
            {"page_number": 3, "text": "The bird arrived on an autumn morning — a small brown thing with an injured wing, unable to fly, landed somehow in his garden among the enormous cabbages. He found it when he came out to check the vegetables and stood looking at it for a long time, uncertain what to do. The bird was so small. His fingers, even at their gentlest, were the size of the bird's whole body. He could not pick it up without risking crushing it. He could not leave it there to die. He stood in his garden as the morning light grew stronger and tried to think of a solution."},
            {"page_number": 4, "text": "The solution, when it came, was patience. He lowered himself very slowly — a process that took five minutes, his great body folding with the care of something that had learned to be careful — until he was lying flat on the ground with his face close to the bird. At this distance he could see it clearly: the bright eye, the damaged wing held at the wrong angle, the rapid flutter of breath. He spoke to it softly, in the low rumble that was his gentlest voice. The bird regarded him without fleeing. He stayed there for an hour, just being present, until the bird seemed to accept that he was not a threat."},
            {"page_number": 5, "text": "He fashioned a nest from moss and leaves, weaving it with fingers that moved more delicately than anyone would have believed possible for their size. He placed food beside it — seeds and insects, gathered with tweezers he had made for precisely such purposes, for moments when the normal scale of his life was too large for the task at hand. He sang to the bird as he sang to his vegetables, low and slow, and over the following days the bird ate and rested and began, very gradually, to heal."},
            {"page_number": 6, "text": "The wing took three weeks to mend. During that time Moss talked to the bird, partly because he was lonely and partly because talking seemed to calm it. He told it about his life on the mountain — the vegetables, the view, the way the stars looked from this height on clear nights. He told it about the valley below and the people who lived there and why he had left. He told it things he had never told anyone because there had been no one to tell. The bird listened or seemed to, tilting its small head at the sound of his voice."},
            {"page_number": 7, "text": "When the bird could fly again, it did not leave. This surprised Moss, who had expected it to return to wherever small brown birds lived when they were not recovering in giants' gardens. Instead it stayed — perching on his shoulder when he worked, sleeping in the nest he had made, singing in the mornings in what he chose to interpret as gratitude. It brought friends: other birds, curious about this strange situation, who came to investigate and stayed when they found that the enormous creature on the mountain was gentle and the singing was good."},
            {"page_number": 8, "text": "By the following summer, Moss's garden was full of birds. They nested in his cabbages and perched on his roof and sang conversations with his vegetable-songs. Word spread, as word does among birds, and more came: injured ones who had heard somehow that this was a place of healing, healthy ones who had heard that this was a place of good singing, curious ones who had heard that this was a place where something unusual was happening. Moss found himself, unexpectedly, no longer alone."},
            {"page_number": 9, "text": "The people from the valley noticed the birds. They had always watched the mountain — keeping track of the giant, maintaining a cautious distance — and the sudden abundance of birds was impossible to miss. A delegation came, for the first time in fifteen years, to see what was happening. They found: a giant lying in his garden surrounded by birds, singing to vegetables and small injured creatures, enormous and gentle and not at all what they had been afraid of. They stood at the edge of the garden and watched. One of them started to cry, though she couldn't have said why."},
            {"page_number": 10, "text": "He came down from the mountain after that — not to live in the valley, his cottage was still his home, but to visit. The people, it turned out, had been afraid of what they imagined he might be, not of what he actually was. What he actually was, they discovered, was patient and kind and very good at fixing things that were broken, whether they were birds or walls or the complicated feelings that people sometimes carried. He still sang to his vegetables. The birds still came. The people still watched from below. But now, sometimes, they sang back. THE END"},
        ]
    },
    "f10ecfac-d2e8-4725-b28e-fee429e5c8ab": {
        "title": "The Lighthouse Keeper's Secret",
        "pages": [
            {"page_number": 1, "text": "The lighthouse had been keeping ships safe for a hundred and forty years, and Mrs Blackwood had been keeping the lighthouse for thirty of them. Every evening at dusk she climbed the two hundred and seventeen steps to the lamp room, and every morning at dawn she climbed them again to extinguish the light. Between those times she maintained the mechanisms, polished the lenses, recorded the weather in her logbook, and watched the sea. The sea, she had learned, was always doing something worth watching. You just had to know how to look."},
            {"page_number": 2, "text": "Her grandson Eli came to stay the summer he turned eleven, sent by parents who thought the sea air would do him good and who needed, perhaps, a break from the particular intensity of raising a child who asked more questions than most adults could answer. He arrived with a suitcase of books and a notebook of his own and the immediate conviction that the lighthouse was the most important place he had ever been. He followed his grandmother up the two hundred and seventeen steps on his first evening and watched the lamp light up the dark sea and did not speak, which Mrs Blackwood appreciated."},
            {"page_number": 3, "text": "She taught him the workings: the mechanism that turned the lamp, the lenses that focused the light, the pattern of flashes — three short, one long — that identified this lighthouse to ships that knew how to read it. She taught him the logbook: how to record wind speed and direction, wave height, visibility, the ships that passed. He learned quickly and carefully, writing in the logbook with the neat handwriting of someone who understood that records mattered. On the fourth day she showed him the other logbook — the one she kept in the drawer beneath the regular one, recording different things entirely."},
            {"page_number": 4, "text": "The other logbook recorded the light in the water. She had noticed it on her third year in the lighthouse — a glow beneath the surface on certain nights, blue-green and shifting, moving in ways that had nothing to do with currents or tides. She had researched it extensively. Some of it was bioluminescence, the natural light of sea creatures. Some of it was not. Some of it responded when she signalled with her lamp, flashing back in patterns that were too regular to be coincidence. She had been recording these exchanges for twenty-seven years. She had never told anyone."},
            {"page_number": 5, "text": "Eli watched the water that night with the careful attention of someone who has been trusted with something important. The glow came after midnight — a soft light rising from the deep water beyond the rocks, spreading and shifting, forming patterns that might have been random but felt intentional. Mrs Blackwood signalled with her hand torch: three short, one long, the lighthouse's signature. The glow below responded: three short, one long, and then something else — a longer sequence, a pattern she hadn't seen before. She recorded it in the other logbook. Eli recorded it in his notebook."},
            {"page_number": 6, "text": "They spent the summer mapping the patterns. Eli had the systematic mind that the project required, and between them they began to build a kind of dictionary — recurring sequences and what they seemed to mean, times of night when the glow was brightest, weather conditions that seemed to affect its behaviour. The glow was not random. It was not just bioluminescence. It was, they agreed, communication — though who or what was communicating, and why, remained unclear. The sea kept its secrets. They kept their records."},
            {"page_number": 7, "text": "On the last week of summer, the storm came. A genuine storm, the kind that justified the lighthouse's existence — wind that shook the tower, waves that crashed against the rocks, rain so heavy the beam could barely cut through it. Mrs Blackwood and Eli stayed in the lamp room all night, maintaining the light, watching the weather. Two ships passed, their lights visible in the chaos, guided safely past the rocks by the beam they had kept burning. When dawn came and the storm eased, the sea was full of light — the glow brighter and closer than they had ever seen it."},
            {"page_number": 8, "text": "The light rose to the surface — not just glowing now but forming, taking shape, becoming something that was not quite solid but was definitely present. It stayed for nearly an hour, illuminating the water around the lighthouse rocks, pulsing in patterns that Mrs Blackwood frantically recorded. Then it sank back into the deep and was gone. They sat in the lamp room as the morning sun rose and looked at each other and did not speak for a long time. Some things, Mrs Blackwood had learned, needed to be felt before they could be discussed."},
            {"page_number": 9, "text": "Eli left at the end of summer with his notebook full of patterns and his head full of questions. He came back every summer after that, and every summer they added to their records, building a body of evidence for something they could not explain but could not ignore. The glow continued. The patterns continued. The exchanges continued. They never discovered what was communicating with them or why it had chosen this lighthouse, this keeper, this careful observer. But they kept asking, in the language of light. Some conversations, they understood, were worth having even without answers."},
            {"page_number": 10, "text": "Mrs Blackwood retired when Eli was twenty-three and old enough, she decided, to take over the lighthouse himself. She left him both logbooks — the official one and the other one, now filling its fourth volume. He climbed the two hundred and seventeen steps every evening and every morning, just as she had done, and he watched the sea, and he kept the light burning, and he continued the conversation with whatever was in the water. The sea, he had learned, was always doing something worth watching. You just had to know how to look. And you had to be patient enough to keep looking, even when the answers didn't come. THE END"},
        ]
    },
    "134d15cb-7824-4e33-a5d8-31f81e8b185f": {
        "title": "The Time Machine Treehouse",
        "pages": [
            {"page_number": 1, "text": "The treehouse at the end of Cassie's garden had been built by her grandfather thirty years ago and had been ordinary ever since, in the pleasant way of treehouses that are well made and well situated and have been the site of enough childhood activity to have accumulated a quality of use that ordinary things sometimes acquire. Cassie was ten, old enough to spend afternoons there alone, reading or watching the garden below or doing nothing in particular. On the Saturday that everything changed, she had gone up to do nothing in particular and found that the east wall, which she had passed a hundred times without incident, had a brass panel on it that she was quite certain had not been there before."},
            {"page_number": 2, "text": "The panel was approximately thirty centimetres square, set into the wood as if it had always been there, with a small screen, several dials, and a keyboard of unusual configuration. The screen displayed text: TEMPORAL DISPLACEMENT DEVICE. CURRENT LOCATION: GARDEN TREEHOUSE, ASHFORD. CURRENT DATE: DISPLAYED BELOW. DESTINATION: ENTER WHEN READY. The current date was correct. Cassie looked at the panel for a long time. She was ten and sensible and good at mathematics and had read enough science fiction to understand what the panel claimed to be, and she was aware that claiming to be a time machine and being one were different things. She typed: Yesterday. The panel hummed. The treehouse vibrated."},
            {"page_number": 3, "text": "Yesterday was Wednesday, and she arrived in it at 4:17pm, which was when she had been in her bedroom doing homework, visible to herself through the treehouse window at the far end of the garden. She sat very still. The panel had brought her here and appeared to be waiting for her to return, which it had indicated would be required by seven o'clock. She had until seven. She thought about what she wanted to do with this and decided to retrieve the library book she had left on the bus, which was practical and low-risk and would also tell her whether the machine worked in ways that mattered — whether the past was something you could actually interact with, or only observe."},
            {"page_number": 4, "text": "The library book was on the bench at the bus stop, exactly where she had left it. She picked it up. It felt real — paper and cover and the particular weight of a medium-sized novel. She stood at the bus stop with her retrieved library book and thought about what it meant that she could hold this, that she had changed yesterday by being in it. The implications were extensive. She walked home — the past version of her home, where her past self was upstairs doing homework — and returned to the treehouse without going inside, not wanting to complicate things further. Back in the treehouse, she told the panel: Return. It brought her back."},
            {"page_number": 5, "text": "She established rules immediately, before the second journey. Look but don't change — beyond the library book, which was done and could not be undone and seemed, on reflection, too small to have consequences. Don't approach herself or anyone she knew in a way that would be remembered. Document everything. The rules were partly about ethics, which she had thought about carefully, and partly about self-preservation — she understood, even at ten, that changing the past could have unpredictable effects on what came after, and that unpredictable effects in her timeline were something to be careful about. She opened her notebook and wrote: Rule 1."},
            {"page_number": 6, "text": "The second journey was to a year she chose carefully: 1960. Her grandmother had been ten in 1960, and her grandmother had told her once about a particular summer's day — a fete in the village, a specific dress, a memory so clear and present that it had survived sixty years with its details intact. Cassie arrived in the village square in summer sunlight and looked. The fete was there. The dress — described precisely enough that she recognised it — was there, on a girl who would one day be her grandmother, eating candyfloss with the focused attention of someone determined to make it last. Cassie watched from a distance and felt time in a way she hadn't before."},
            {"page_number": 7, "text": "She developed a methodology over the following months. Short visits first — hours rather than days — to understand each period's context before going in further. Research beforehand, using the library and the internet, so she knew what to expect. Notes during, detailed and precise, written immediately on return while the experience was still clear. She visited: the building of the first railway bridge in the area, 1847, standing above the construction site in cold spring light. A storm in 1987 that her father had told her about, watching from the treehouse as it rolled in from the west, enormous and vivid. The field that had existed before the houses, 1920, sitting in open farmland with no road visible in any direction."},
            {"page_number": 8, "text": "The panel disappeared when anyone else climbed up. She had tested this carefully — sending her younger brother up on a pretext, watching from below as he arrived and found only the east wall, the plain wood, nothing brass or anomalous. When he climbed down and she climbed up, it was there. She had thought about telling someone and had concluded that the decision was connected to what the panel's behaviour seemed to indicate: it had found her specifically, and the treehouse's choice to show itself only to her seemed worth respecting. She kept the logbook in a box under the treehouse floor. She told no one."},
            {"page_number": 9, "text": "The most important journey was the last one she would record in the first logbook: to a morning in 1892, specifically to this garden, specifically to the place where the great oak tree stood. She had researched when it was planted — a council record, unexpectedly detailed, gave a date. She arrived in October 1892 and watched a man plant a sapling: very young, barely knee-high, its root ball wrapped in burlap. He was careful with it. He was, she could tell, someone who understood that he was planting something for a future he wouldn't see. She watched him until he was done and then she looked at the sapling, which would become the oak that held her treehouse, and felt the particular vertigo of being in the middle of a very long story."},
            {"page_number": 10, "text": "She was twelve when she filled the first logbook. The second was already half-full. She had forty-nine documented journeys, a methodology that had improved with every trip, and a relationship with time that was different from anyone else's she knew — more layered, more aware of its depth in both directions. She sat in the treehouse on her birthday and opened the panel and looked at the destination field. She had a list of places she wanted to go, carefully researched and prioritised. The list was long enough to occupy years. She looked at the oak tree's branches around her — the oak that a man in 1892 had planted carefully, for someone he would never meet — and thought about all the time that was available, in both directions, if you were paying attention. She typed the next destination. THE END"},
        ]
    },
    "61dced03-0e50-4d76-826a-640b9ffa0f19": {
        "title": "The Underground City",
        "pages": [
            {"page_number": 1, "text": "Fen found the entrance on a Tuesday, which was not a day she associated with extraordinary things, though she conceded afterward that extraordinary things didn't particularly care what day it was. She had been walking the long path through the old hill — a shortcut between the village and the farm that had been used for decades — when she noticed that the crack in the rock face she passed every day was, today, noticeably wider. Wide enough to look into. She looked in. Dark, then less dark as her eyes adjusted, then a tunnel, going inward further than the hill's exterior width could account for. She turned on her phone torch. She went in."},
            {"page_number": 2, "text": "The tunnel went for twenty minutes of walking — slightly downward, gently curving, the walls dry and carved with enough regularity to be clearly not natural. At the end of the tunnel the ceiling abruptly rose and she stepped out into a street. She stood on a pavement of flat cut stones and looked up at carved rock thirty feet above her, and looked along a street of buildings set back behind stone-edged paths, lit by what she would later identify as bioluminescent moss in glass-covered channels running along the walls. Someone passed her, going the other way — small, pale-eyed, with the composed expression of someone going about their day who has seen the occasional surface person before. 'Tourist?' they said. 'Yes,' said Fen. 'This way,' said the small person."},
            {"page_number": 3, "text": "Her guide's name was Silt, and she had been a guide for forty years, long enough to have developed a manner that was efficient without being unwelcoming, informative without being exhausting, and gently corrective of the most common surface-person errors without making them feel inadequate. She showed Fen the street map — carved into the stone at the main junction, detailed and updated regularly — and oriented her. The underground city was called the Underway, and it had been here for five hundred years, and it was organised vertically rather than horizontally, with the deepest levels considered the most prestigious, and it had a population of approximately twelve thousand, and it was, Silt said, generally not secret but not advertised."},
            {"page_number": 4, "text": "The market was the first destination on any tour, Silt said, because it was where you understood most quickly what the Underway was and how it worked. It occupied a natural cavern that had been extended and refined over centuries, and it contained: crystals in every variety and colour, from the functional to the purely beautiful; root vegetables in shapes that grew differently underground than on the surface; fungi of dozens of kinds, some edible and some medicinal and some purely ornamental; carved goods in stone and bone and wood that had to be traded down from the surface; and the fish that had evolved in the Underway's deep lakes, eyeless and pale and moving through the water with the effortless precision of things that had found their perfect medium."},
            {"page_number": 5, "text": "She bought a small purple crystal from a vendor who explained its properties: it held heat for longer than its size should permit and released it slowly, making it useful in cold chambers. She also bought a root vegetable she couldn't identify, which the vendor said tasted of something she would find familiar, and which turned out to taste precisely of butterscotch, which she had not expected but thoroughly appreciated. Silt watched her buy these things with the patient expression of someone who has watched surface people discover the market many times and finds their reactions reliably endearing. 'Most people buy too much on the first visit,' Silt said. 'Because they think they won't come back.' 'Will I come back?' Fen asked. 'Most do,' said Silt."},
            {"page_number": 6, "text": "The district structure of the Underway became clearer as Silt walked her through it. The upper levels were commercial and communal — the market, the guild halls, the schools, the administrative buildings. The middle levels were residential, the homes carved into the rock with varying degrees of elegance and spaciousness. The deep levels — accessed by lifts that used counterweight systems powered by the underground water — were the oldest and most prestigious, some of them occupied by families who had been in the same chambers for two hundred years. 'How do you find new space?' Fen asked. 'You carve it,' Silt said simply. The Underfold were, she added, extraordinary carvers. They had been for five hundred years."},
            {"page_number": 7, "text": "The museum was at the deepest point of the city, as Silt had said it would be, in chambers that were the oldest continuously occupied spaces in the Underway. The exhibits were arranged chronologically: the tools of the first excavation, the founding documents in their original cases, the maps that showed the city's growth from a single tunnel to its current extent. And the founding story, told in painted panels around the walls: the Underfold had not always lived underground. Five hundred years ago, during a long surface winter that had lasted a decade, their ancestors had moved below ground initially for survival and had found something they had not expected — a belonging. They had stayed."},
            {"page_number": 8, "text": "Silt took her to the deep lake on the second level below the museum — a body of water that occupied a cavern so large its ceiling was lost in darkness above them, its surface lit by the bioluminescent organisms that lived in it. The fish were visible from the lake's edge: pale shapes moving in the lit water, their eyeless navigation somehow more purposeful than the seeing kind. Silt said the fish had been adapting to underground life for the full five hundred years of the Underway's existence, and that the biologists in the city tracked their evolution the way surface scientists tracked surface species. 'Five hundred years is not very long,' Silt said. 'But it is enough to begin changing.'"},
            {"page_number": 9, "text": "The evening in the Underway was marked by a dimming of the bioluminescent channels rather than a sunset — a shift from the bright active level of day to the softer, warmer level of evening and then the minimal level of night. Fen had been there for six hours. Silt walked her back to the tunnel entrance with the manner of someone completing a satisfactory day's work. She gave Fen a small card — the tourist card of the Underway, with a map on one side and visiting information on the other, including the instruction: Tell no one who would not treat this carefully. Fen looked at the card and then at the entrance and then at Silt. 'What if I want to come back?' she asked. 'Use the entrance you came in,' Silt said. 'It will still be here.'"},
            {"page_number": 10, "text": "She emerged into the hillside path in the late afternoon light, the purple crystal in her pocket and the butterscotch root eaten entirely on the walk back through the tunnel. The surface world looked different — brighter, more exposed, the sky improbably large after six hours of stone ceilings. She stood on the path and looked at the hill and thought about the twelve thousand people inside it, going about their days in the carved warmth of the Underway, the fish in the deep lake adapting slowly, the museum at the deepest point holding five hundred years of a people who had found where they belonged. She took out the tourist card. Tell no one who would not treat this carefully. She put it in her pocket carefully, walked home, and began to think about who that might be. THE END"},
        ]
    },
    "5ebe3908-18f9-4947-b049-7248c2700fa4": {
        "title": "The Unicorn's Rainbow Bridge",
        "pages": [
            {"page_number": 1, "text": "The Rainbow Bridge was the oldest structure in the enchanted lands and the most important. Seven arches of pure colour spanning the sky from the Valley of Sunrise to the Mountains of Moonrise, maintained each dawn by the unicorn herd who crossed it with the morning light, their hooves spreading colour into the world below as they went. Without the Bridge's daily crossing, the world would grey: not instantly, not dramatically, but gradually, the way colour leaves a painting left too long in the sun. The Bridge had been crossed every dawn for ten thousand years. Lyra was the youngest member of the herd assigned to cross it, and she had been crossing it for two years without incident."},
            {"page_number": 2, "text": "The morning she found the problem, she arrived before the others. She had been doing this for weeks — arriving early to watch the Bridge before the crossing, to understand it better, to see it in the pre-dawn light before the herd's passage activated it. What she saw this morning stopped her. The red arch — the first arch, the one that carried the frequency of red into the world and sustained the poppies, the robins, the autumn leaves, the fire of sunsets — was fading. Not gone, not yet, but a grey-tinged pallor where the pure red should have blazed. She pressed her horn to the arch's base. The colour she received back was wrong: attenuated, weak, missing something essential."},
            {"page_number": 3, "text": "The elder unicorns confirmed what she had felt. The arch was failing — the source of its colour, which was a fire-flower in the Valley of Embers, was not generating the intensity it needed to maintain the Bridge's red. They had seen this before, twice in the herd's recorded history. Both previous times the problem had been corrected by a journey to the Valley of Embers to renew the connection. Both previous times, the journey had been attempted by experienced unicorns and had taken multiple attempts. Lyra listened to this history carefully. Then she said she would go. The elders looked at her. She was young. She was also, they acknowledged, already the one who had found the problem."},
            {"page_number": 4, "text": "The Valley of Embers was southeast of the Bridge, three days' travel through terrain that shifted character with the compass point: the meadowlands and then the rocky highland and then the thermal country, where the ground was warm underfoot and the air smelled of minerals and the fire-flowers grew in the places where the earth's heat came closest to the surface. Lyra knew the route from the herd's records, which she had studied carefully before departing. She moved steadily, not rushing — rushing, the records said, was one of the previous failures' contributing factors. The Valley required patience, not speed."},
            {"page_number": 5, "text": "The fire-flowers were remarkable — plants that burned continuously without being consumed, their petals and leaves made of living flame in shades from deep blue-white at the root to brilliant red-gold at the tips. They were not hot in the way fire was hot: approaching one felt like standing in concentrated sunlight, warm and vivid, not burning. The largest ones lined the Valley's central path, which the records described as the Approach, and they had a quality of awareness — they turned slightly as she walked among them, the way sunflowers turned, tracking not heat but something she didn't have a word for. Lyra walked the Approach carefully, without hurrying, being present to each flower as she passed."},
            {"page_number": 6, "text": "At the Valley's centre was the oldest fire-flower. She recognised it from the records' descriptions: its flame was deeper and more complex than the others, containing colours she couldn't name, burning with an intensity that should have been painful at close range but wasn't. She stood before it for a long time. The renewal required physical contact — horn to the flower's centre — and she had been warned that the connection was overwhelming the first time, that the previous unicorns had needed to retreat and approach again. She breathed steadily. She let the Valley's warmth settle into her. Then she moved forward, slowly, and pressed her horn to the fire-flower's heart."},
            {"page_number": 7, "text": "The warmth that entered her was not like anything she had carried before. It moved through her horn and through her whole body in a wave that was simultaneously heat and light and something she could only describe as the specific quality of red itself — the colour as an experience rather than a perception. She stood with it, not retreating, letting it find its level in her. It settled into something sustainable — vivid but not overwhelming, warm but not burning. The fire-flower pulsed once, deeply, in what she felt as acknowledgement. She stepped back. She was glowing. Her white coat held a red radiance that lit the Valley around her."},
            {"page_number": 8, "text": "The return journey took four days, not three. She moved more carefully now, aware of what she carried, mindful of the red radiance that spread outward from her as she walked. She noticed its effect: the fire-flowers she passed on the Valley's edge turned toward her as she went, their own flames briefly brighter. The rock on the highland path seemed warmer. In the meadowlands, the grass where she walked grew denser, greener, as if the red she carried activated something dormant in the soil. She arrived at the Bridge at dawn on the fourth day, the herd assembled and waiting. The elder who had first assessed the problem came to meet her and looked at her coat's radiance. 'You held it fully,' she said. 'Yes,' said Lyra."},
            {"page_number": 9, "text": "She ran the Bridge at the morning crossing. The herd crossed in order of seniority, Lyra last as the youngest, and as she ran the first arch the red radiance poured from her into the arch's structure with a sound she felt rather than heard: a deep resonant note, the frequency of red, sustained and pure. The arch blazed back to full intensity, its colour more vivid than it had been in months. Below, she could see the world responding: poppies opening, the robins on their telegraph wires suddenly bright-breasted, the autumn leaves on the valley trees catching fire with their proper red. The herd watched from the far side. When she crossed the final arch and joined them, the eldest unicorn said nothing. She simply touched her horn briefly to Lyra's, which was the highest acknowledgement the herd gave."},
            {"page_number": 10, "text": "The Bridge continued its daily crossings, as it had for ten thousand years. Lyra crossed it every dawn with the others, each time feeling the red arch's renewed strength under her hooves. She made the journey to the Valley of Embers every ten years after that — it became her role, the youngest unicorn's task becoming the keeper's task, the journey she knew how to make now and could make again when it was needed. She taught the next youngest unicorn the route and the patience and what it felt like to carry the warmth of a fire-flower's heart back through three days of terrain. The Bridge blazed every morning. The world kept its colour. The work continued. It always continued. That, Lyra understood, was not a burden but a gift: always something worth doing, always a dawn worth running toward. THE END"},
        ]
    },
    "67b40688-b6cb-431b-a0c6-8baa1c28542c": {
        "title": "The Wizard's Apprentice",
        "pages": [
            {"page_number": 1, "text": "The Wizard Aldous had been looking for an apprentice for thirty years, which was unusual — most wizards found one within five. He had interviewed four hundred and twelve candidates. Every one had failed, for different reasons: the arrogant ones couldn't be taught, the timid ones couldn't be pushed, the careless ones couldn't be trusted, the overly careful ones couldn't improvise. He had developed, through four hundred and twelve interviews, a very specific sense of what he needed. He needed someone who asked the question that wasn't being asked. He had not, in thirty years, met such a person, which was why when Mira turned up at his tower door on a rainy Thursday without an appointment and dripping on his step, his first response was to open the door wider."},
            {"page_number": 2, "text": "She was twelve, with the kind of directness that comes from having always been more interested in things than in what other people thought of her interest. She had found out about Aldous through a library book, tracked down his tower through local records, and arrived on a Thursday because she had read that wizards were traditionally more receptive to visitors at the change of the week. The book had been written in 1743 and this information may have been inaccurate, but she had brought it anyway as evidence of preparation. She held it up in the rain. Aldous looked at the book, then at her sparking left hand — she had been practising the basic exercises in chapter three — and said: 'You're late.' 'I didn't know I was coming,' said Mira. 'I know,' said Aldous. 'Come in.'"},
            {"page_number": 3, "text": "The tower's interior was larger than its exterior could account for, which she filed under things to investigate. Every wall was shelves. Every shelf was books, or instruments, or jars of things that ranged from mundane to alarming. Footnote the cat examined her from a position on a high shelf, sneezed once in what the wizard said was approval, and went back to sleep. Aldous showed her the ground floor without speaking much — the workroom, the library, the records, the supply rooms — and watched how she looked at things. She looked at everything carefully, which was the correct response. She asked two questions, both good ones. She noticed the tower's secondary staircase, which most people missed entirely. 'You'll do,' said Aldous, which she would later learn was the highest thing he said."},
            {"page_number": 4, "text": "The first formal lesson was observation, and it involved no magic at all. She was sent to the garden with instructions to return in three hours and report what she had noticed. She brought back four pages of notes, which was more than Aldous had received from any previous candidate and significantly more detailed. She had noted the garden's formal layout and the places where it had exceeded its formal intent. She had identified seven plant species, three of which were unusual for the altitude. She had noted the bees' flight patterns and what they implied about the location of their hive. She had noted the second gate in the back wall that wasn't on any exterior survey of the property. 'This gate,' said Aldous. 'What did you make of it?' 'You use it,' she said. 'But not recently.' He nodded. 'How do you know?' She showed him the evidence. He nodded again."},
            {"page_number": 5, "text": "The magic was harder than she had expected, which was the most consistent thing about magic: it was always harder than expected. She had thought that knowing the theory — having read chapter three, and chapters four through nine in the weeks before arriving — would provide a foundation. It provided a vocabulary, which was different. The actual doing of magic required connecting the vocabulary to something internal that she didn't have a name for yet, a quality of intention combined with something Aldous called sensory precision, which meant knowing exactly what you were trying to produce before you tried to produce it. She turned seventeen things into other things by accident in the first month, most of them temporary, one of them Footnote."},
            {"page_number": 6, "text": "Footnote forgave her relatively quickly — cats being practical about these things — but the experience was instructive. The lesson Aldous drew from it was the one she had already identified herself: she had acted before fully specifying her intention, which was the most common error and also the most consequential. 'Magic responds to what you actually want,' he said, 'not what you think you want. They are frequently different.' She spent the next month on intention exercises — not casting anything, just practising the complete specification of desired outcomes before any implementation. It was slow and frustrating and resulted in significant improvement. 'Patience and precision,' Aldous said. 'Everything else follows from those.'"},
            {"page_number": 7, "text": "She began to find her way into the tower's deeper library — the back shelves, the locked cases whose keys Aldous gave her one by one as he assessed her readiness, the rolled documents in the upper room that contained working records going back three centuries. She was particularly interested in the failures: Aldous kept meticulous records of things that hadn't worked, which she found more instructive than the successes. Each failure was documented with the hypothesis, the implementation, the result, and the analysis. Reading them, she began to understand the pattern of errors that accumulated across centuries of magical practice — the same mistakes made in different forms, the same assumptions that proved wrong, the same resistance that experience provided against being wrong in those particular ways again."},
            {"page_number": 8, "text": "Her specialisation emerged in year two, unexpectedly. She had been working on a problem Aldous had set — a complex enchantment that had broken down and needed diagnosing — and had approached it in the way she approached everything: by first making absolutely sure she understood what the problem actually was, rather than what it appeared to be. In doing so she identified that the breakdown was not where Aldous thought it was, and that the correct repair was fundamentally different from the one he had been attempting. She showed him her analysis carefully, because she knew he had been working on this for ten years. He sat very still afterward for quite a long time. Then he said: 'That's why I was looking for you.'"},
            {"page_number": 9, "text": "She asked him, in year three, what had happened to the previous four hundred and twelve candidates. He told her: some had gone on to be adequate wizards. Some had found other callings. Several had been exceptional in other ways that simply hadn't been what he needed. A handful he had misjudged — rejected when he shouldn't have, a source of regret he was direct about. 'What made me different?' she asked. He considered. 'You asked why the gate wasn't in the survey,' he said. 'Every other candidate looked at the gate and thought: there's a gate. You looked at it and thought: why doesn't the record show this gate? Different question. The whole practice of magic is in the difference between those two questions.'"},
            {"page_number": 10, "text": "She was a qualified wizard at seventeen, the shortest apprenticeship on record, which embarrassed her somewhat because she felt there was still more to learn, which Aldous said was a good sign and not a bad one. She stayed in the tower for five more years anyway, as a colleague rather than an apprentice, working on problems that interested them both. Footnote remained on the high shelf. The secondary staircase remained slightly mysterious. The garden remained slightly beyond its formal design. When she eventually left to establish her own practice, she took the four pages of notes from the first observation exercise and pinned them above her workbench. Not because they were particularly impressive — she could do much better now — but because they showed her where she had started from, and starting was the thing, she had learned, that everything else required. THE END"},
        ]
    },
}

async def import_batch3c():
    client = AsyncIOMotorClient(os.environ.get('MONGO_URL'))
    db = client[os.environ.get('DB_NAME', 'test_database')]
    
    print('='*60)
    print(' APPLYING - Batch 3C Import (11 remaining books)')
    print('='*60)
    
    total_created = 0
    
    for book_id, book_data in BOOKS_DATA.items():
        book = await db.books.find_one({'id': book_id})
        if not book:
            print(f'❌ Book not found: {book_data["title"]}')
            continue
        
        title = book.get('title', 'Unknown')
        
        # Check existing pages
        existing = await db.pages.count_documents({'book_id': book_id})
        if existing > 0:
            print(f'⚠️ {title}: Already has {existing} pages - skipping')
            continue
        
        # Create pages
        embedded_pages = []
        for page_data in book_data['pages']:
            page_id = str(uuid.uuid4())
            new_page = {
                'id': page_id,
                'book_id': book_id,
                'page_number': page_data['page_number'],
                'text_content': page_data['text'],
                'image_url': None,
                'audio_url': None,
                'created_at': datetime.now(timezone.utc).isoformat(),
                'updated_at': datetime.now(timezone.utc).isoformat()
            }
            await db.pages.insert_one(new_page)
            embedded_pages.append({
                'id': page_id,
                'page_number': page_data['page_number'],
                'text_content': page_data['text'],
                'image_url': None,
                'audio_url': None
            })
        
        # Update book with embedded pages
        await db.books.update_one(
            {'id': book_id},
            {'$set': {'pages': embedded_pages}}
        )
        
        print(f'✅ {title}: {len(book_data["pages"])} pages created')
        total_created += len(book_data['pages'])
    
    print('='*60)
    print(f' Total pages created: {total_created}')
    print('='*60)
    
    client.close()

if __name__ == "__main__":
    asyncio.run(import_batch3c())
